// The editor preview renders exactly what the cube does: the same vectors the C++ test checks
// (show_vectors.json is generated by `python pairing_station/showfile.py --header`).
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { Player, testRng, lerp8, levelHex, hexLevels, parseTime, fmtTime, problem, retype, fanOffset, scatter, parseCubes } from '../lib/showengine.js';

const { doc, cubes } = JSON.parse(readFileSync(new URL('./show_vectors.json', import.meta.url), 'utf-8'));

test('renders the cross-engine vectors for every cube number (fanning included)', () => {
  for (const [cube, rows] of Object.entries(cubes)) {
    const player = new Player(doc, Number(cube)), rng = testRng();
    for (const [t, playing, r, g, b] of rows) {
      const got = player.render(t, rng);
      assert.equal(got !== null, playing === 1, `cube ${cube} t=${t}`);
      assert.deepEqual(got || [0, 0, 0], [r, g, b], `cube ${cube} t=${t}`);
    }
  }
});

test('fan offsets and cube lists', () => {
  const seq = { fan: { mode: 'sequential', step_ms: 250, groups: 4 } };
  assert.deepEqual([0, 1, 2, 4, 5].map((c) => fanOffset(seq, c)), [0, 0, 250, 750, 0]);
  assert.equal(scatter(17), Number((17n * 2654435761n) % 4294967296n >> 16n));
  assert.deepEqual(parseCubes('1-3, 7 5'), [1, 2, 3, 7, 5]);
  assert.equal(parseCubes('1-x'), null);
});

test('lerp truncates toward zero like C', () => {
  assert.equal(lerp8(17, 11, 1500, 3000), 14);
  assert.equal(lerp8(17, 16, 1500, 3000), 17);
  assert.equal(lerp8(0, 100, 5000, 5000), 100);
});

test('colour and time helpers', () => {
  assert.equal(levelHex([100, 0, 50]), '#ff0080');
  assert.deepEqual(hexLevels('#ff0080'), [100, 0, 50]);
  assert.equal(parseTime('1:14.3'), 74300);
  assert.equal(parseTime('36'), 36000);
  assert.equal(parseTime('x'), null);
  assert.equal(fmtTime(74300), '1:14.300');
});

test('problem() and retype()', () => {
  assert.equal(problem(doc), null);
  const bad = JSON.parse(JSON.stringify(doc));
  bad.cues[1].start_ms = 0;
  assert.match(problem(bad), /must start after/);
  const cue = retype({ start_ms: 5, label: 'x', type: 'solid', colours: [[1, 2, 3]], params: {} }, 'cycle');
  assert.deepEqual(cue, { start_ms: 5, label: 'x', type: 'cycle', colours: [[1, 2, 3]], params: { step_ms: 1000 } });
  assert.equal(retype(cue, 'fade').colours.length, 2);
});
