// devices: see ../ko.js.
export default {
  // panels/common.js
  'port': '포트',
  'firmware': '펌웨어',
  'Identify again': '다시 식별',
  'Ask the board what it is (no reset)': '보드에 정체를 묻습니다 (리셋 없음)',
  'Unpin': '고정 해제',
  'Disconnect': '연결 해제',
  'Connect': '연결',
  'Inventory:': '인벤토리:',
  'Console': '콘솔',
  'Recent jobs on this port': '이 포트의 최근 작업',

  // panels/sections.js
  'Pool light test': '풀 조명 테스트',
  'PoolRadioTest bridge (emulates radios 1-6)': 'PoolRadioTest 브리지 (라디오 1-6 에뮬레이션)',
  'Pool central diagnostics': '풀 중앙 진단',
  'Pool central controller': '풀 중앙 컨트롤러',
  'Pool slider calibration': '풀 슬라이더 보정',
  'A PoolZone radio (zone type 3)': 'PoolZone 라디오 (존 종류 3)',
  'Preshow cue test': '프리쇼 큐 테스트',
  'A PreshowZone plate (zone type 1)': 'PreshowZone 플레이트 (존 종류 1)',
  'Preshow bridge status': '프리쇼 브리지 상태',
  'The TouchDesigner media bridge': 'TouchDesigner 미디어 브리지',
  'ESP-NOW range test': 'ESP-NOW 거리 테스트',
  'A range-test board (RX unit)': '거리 테스트 보드 (RX 유닛)',
  'Bench tools': '벤치 도구',
  'Diagnostics that need a particular board on USB.': '특정 보드를 USB로 연결해야 하는 진단입니다.',
  'needs:': '필요:',
  'Open': '열기',
  'not attached': '연결 안 됨',
  'Settings': '설정',
  'Appearance': '화면',
  'Theme': '테마',
  'Dark': '어둡게',
  'Light': '밝게',
  'Match the system': '시스템 설정 따르기',
  'Behaviour': '동작',
  'Open a live session automatically for every identified board': '식별된 모든 보드에 실시간 세션을 자동으로 엽니다',
  'Preview the selected cube with a 1 s flash (pairing station)': '선택한 큐브를 1초 점멸로 미리 보기 (등록 스테이션)',
  "Audio cues for USB cube flashing (the cube flasher's sounds: plugged in, start, each stage, success, failure)": 'USB 큐브 플래시 소리 알림 (큐브 플래셔의 소리: 연결, 시작, 각 단계, 성공, 실패)',
  'Test sound': '소리 테스트',
  'Automatic updates': '자동 업데이트',
  'Zone databases over the air: the link with an NFC reader (else the first zone relay) walks the zone database to every out-of-date zone in range': '무선 존 데이터베이스: NFC 리더가 있는 링크(없으면 첫 번째 존 릴레이)가 범위 안의 오래된 존에 존 데이터베이스를 차례로 보냄',
  'Zone databases over USB: database-only update for any configured zone board plugged in that is behind': 'USB 존 데이터베이스: 꽂힌 설정 완료 존 보드의 데이터베이스가 뒤처져 있으면 데이터베이스만 업데이트',
  'Main show over the air: cubes in range on an older show are updated (a Workstation or General Radio; never mid-show)': '무선 메인쇼: 범위 안에서 이전 쇼를 가진 큐브를 업데이트 (Workstation 또는 General Radio, 쇼 진행 중에는 안 함)',
  'Pull a newer zone database and show from the web (needs the web password)': '웹에서 더 새로운 존 데이터베이스와 쇼를 받아오기 (웹 비밀번호 필요)',
  'Saved on this computer; on by default.': '이 컴퓨터에 저장되며 기본값은 켜짐입니다.',
  'Keyboard': '키보드',
  'close a tooltip, else stop every active operation': '툴팁 닫기, 없으면 진행 중인 모든 작업 중지',
  'search': '검색',
  'sections': '섹션',
  'move the rail selection': '레일 선택 이동',
  'this list': '이 목록',
  'About': '정보',
  'Database': '데이터베이스',
  'disabled': '비활성',
  'SIMULATION (fake boards, temporary database copy)': '시뮬레이션 (가상 보드, 임시 DB 사본)',
  'live': '실제 운영',
  'Repository': '저장소',
  'Unknown cube': '알 수 없는 큐브',
  'No inventory record for': '인벤토리 기록 없음:',
  'Cube without a number': '번호 없는 큐브',
  'heard {ago} ago': '{ago} 전 수신',
  'not heard this session': '이번 세션에 수신 없음',
  'USB pinned': 'USB 고정됨',
  'Unknown zone': '알 수 없는 존',
  'No registry record for': '레지스트리 기록 없음:',
  'in range {rssi}': '범위 안 {rssi}',
  'last seen {when}': '마지막 수신 {when}',
  'never': '없음',
  'Type / point': '종류 / 포인트',
  'v{v} · {n} records · CRC {crc}': 'v{v} · 기록 {n}개 · CRC {crc}',
  'Stats': '통계',
  '{tags} tags · {unknown} unknown · {fail} send failures · uptime {uptime}': '태그 {tags} · 알 수 없음 {unknown} · 전송 실패 {fail} · 가동 {uptime}',
  '(not applied)': '(미적용)',
  'never reported': '보고 없음',
  '{when} via {source}': '{when} · {source} 경유',
  'Over the air (via the station / dongle)': '무선 (스테이션 / 동글 경유)',
  'Update database over the air': '무선으로 DB 업데이트',
  'Unicast announce + broadcast chunks until the zone reports the new version and CRC.': '존이 새 버전과 CRC를 보고할 때까지 유니캐스트 알림과 브로드캐스트 청크를 보냅니다.',
  'Identify (10 s)': '식별 (10초)',
  'Request tap log': '태그 기록 요청',
  'Reboot': '재부팅',
  'ZONE_REBOOT over the radio.': '무선으로 ZONE_REBOOT.',
  'Set RX gain': 'RX gain 설정',
  "ZONE_SET_CONFIG; confirmed only by the zone's next settings report.": 'ZONE_SET_CONFIG. 존의 다음 설정 보고로만 확인됩니다.',
  'Connect a pairing station or ESP-NOW dongle with zone support to talk to this zone.': '이 존과 통신하려면 존 지원 등록 스테이션 또는 ESP-NOW 동글을 연결하세요.',
  'Tap log ({n})': '태그 기록 ({n})',
  '{s} s ago': '{s}초 전',
  'unknown': '알 수 없음',

  // panels/ZonePanel.js
  'not in inventory': '인벤토리에 없음',
  'no command sent yet': '아직 보낸 명령 없음',
  'Cube': '큐브',
  'Result': '결과',
  'Held': '유지',
  'on plate': '플레이트 위',
  'Inventory': '인벤토리',
  'no reader status yet': '리더 상태 없음',
  'Unknown tag': '알 수 없는 태그',
  'No cube on the plate': '플레이트에 큐브 없음',
  "— (not in this zone's database)": '— (이 존의 DB에 없음)',
  'Zone sent': '존 전송',
  'Cube shows': '큐브 표시',
  '— (unknown tags are ignored by zones)': '— (존은 알 수 없는 태그를 무시함)',
  'Taps': '태그 횟수',
  '{n} this session': '이번 세션 {n}회',
  "This tag is not in the plate's database. See Attention for what the inventory knows about it.": '이 태그는 플레이트 DB에 없습니다. 인벤토리가 아는 내용은 Attention을 확인하세요.',
  'Actions apply to cube #{n}': '동작 대상: 큐브 #{n}',
  'Actions apply to the cube on the plate, or to a selected history row': '동작 대상: 플레이트 위의 큐브 또는 선택한 이력 행',
  'Flash 5 s': '5초 점멸',
  'Clear (idle white)': '해제 (대기 흰색)',
  'Sends SET_ZONE 0 to the cube.': '큐브에 SET_ZONE 0을 보냅니다.',
  'Sends SET_ZONE {zone} ({name}) to the cube.': '큐브에 SET_ZONE {zone} ({name})을 보냅니다.',
  'Stop flashing': '점멸 중지',
  'History': '이력',
  'No taps yet': '아직 태그 없음',
  'Zone console': '존 콘솔',
  "tag of cube {cube} ({status}) — not in this plate's database": '큐브 {cube}의 태그 ({status}) — 이 플레이트 DB에 없음',
  'pending tag of {cube} ({status})': '{cube}의 대기 중 태그 ({status})',
  'unknown to this computer': '이 컴퓨터에 알려지지 않음',
  'off (Settings › Automatic updates)': '꺼짐 (설정 › 자동 업데이트)',
  'on · current': '켜짐 · 최신',
  'on · {result}': '켜짐 · {result}',
  'on · starting': '켜짐 · 시작 중',
  'on': '켜짐',
  'Board': '보드',
  '{firmware} · {name} · type {type} point {point}': '{firmware} · {name} · 종류 {type} 포인트 {point}',
  'unconfigured': '설정 안 됨',
  'no zone report': '존 보고 없음',
  'Board database': '보드 DB',
  'Published database': '게시 DB',
  'local mappings differ (Sync to publish)': '로컬 매핑이 다름 (Sync로 게시)',
  'nothing published': '게시본 없음',
  'Automatic database update': '자동 데이터베이스 업데이트',
  'Local build': '로컬 빌드',
  'Update database over USB': 'USB로 DB 업데이트',
  'Check report': '보고 확인',
  'Identify via bootloader': '부트로더로 식별',
  'Reads flash through the bootloader and reboots the board.': '부트로더로 플래시를 읽고 보드를 재부팅합니다.',
  'Reboot (over the air)': '재부팅 (무선)',
  'Sends ZONE_REBOOT over the radio.': '무선으로 ZONE_REBOOT를 보냅니다.',
  'Identity': '신원',
  'Name': '이름',
  'Flash firmware + identity + database': '펌웨어 + 신원 + DB 플래시',
  'Force flash': '강제 플래시',
  'REFUSED: {label}. Force flashing a cube unregisters it.': '거부됨: {label}. 큐브를 강제 플래시하면 등록이 해제됩니다.',
  'Apply RX gain {db} dB now': 'RX gain {db} dB 지금 적용',
  'Stores and applies the reader gain over the console.': '콘솔을 통해 리더 게인을 저장하고 적용합니다.',
  'build it under This computer › Firmware builds.': 'This computer › Firmware builds에서 빌드하세요.',
  'Control points sent; Apply & save writes them to flash': '제어점을 보냈습니다. 적용 및 저장을 눌러야 플래시에 기록됩니다',
  'Override output without a cube': '큐브 없이 출력 오버라이드',
  'Leased: the console pings the radio every 0.35 s; the lease lapses 1.5 s after it stops.': '리스: 콘솔이 0.35초마다 라디오에 신호를 보내며, 멈추면 1.5초 뒤 리스가 만료됩니다.',
  '{mm} mm · index {index}': '{mm} mm · 인덱스 {index}',
  'waiting for {what}': '{what} 대기 중',
  'Saved calibration loaded': '저장된 보정 불러옴',
  'Calibration is not saved on the board': '보정이 보드에 저장되지 않았습니다',
  'Control points': '제어점',
  'Member': '구간',
  'Anchor': '기준점',
  'Set to': '설정값',
  'Capture': '측정값 넣기',
  'Send control points': '제어점 보내기',
  'Apply & save to flash': '적용 및 플래시에 저장',
  "Writes the calibration to the radio's flash.": '보정을 라디오 플래시에 기록합니다.',
  'Reload saved': '저장값 다시 불러오기',
  'Saved calibration loaded (saved=true)': '저장된 보정 불러옴 (saved=true)',
  'Tuning': '튜닝',
  '(not supported by this firmware; update to pool-2.8.0 or newer)': '(이 펌웨어는 지원하지 않음. pool-2.8.0 이상으로 업데이트)',
  'saved to flash': '플래시에 저장됨',
  'live only, not saved': '실시간만 적용, 저장 안 됨',
  'Apply live': '실시간 적용',
  'Apply & save': '적용 및 저장',
  'Writes tuning to flash.': '튜닝을 플래시에 기록합니다.',
  'Firmware defaults': '펌웨어 기본값',
  'Diagnostics': '진단',
  'Radio id': '라디오 ID',
  'Central sees me': '중앙 수신 여부',
  'yes': '예',
  'NO': '아니오',
  'Send errors': '전송 오류',
  'Queued': '대기열',
  'Override': '오버라이드',
  'Delivery': '전달',
  'Central': '중앙',
  '{mac} · seen {ms} ms ago': '{mac} · {ms} ms 전 수신',
  'Cube on plate': '플레이트 위 큐브',
  'Reader': '리더',
  'filtered distance (mm)': '필터링된 거리 (mm)',
  'flicker {flicker} · missed {missed} · settle {settle}': '깜빡임 {flicker} · 놓침 {missed} · 안정화 {settle}',
  'Stride (ticks)': '간격 (눈금)',
  'Hold (s)': '유지 (초)',
  'Start guided recording': '안내 녹화 시작',
  'Streams raw samples from the radio (RAW ON) until the recording ends or is aborted.': '녹화가 끝나거나 중단될 때까지 라디오에서 원시 샘플을 받습니다 (RAW ON).',
  'No live session': '실시간 세션 없음',
  'No calibration report yet': '아직 보정 보고 없음',
  'This firmware has no tuning support (pool-2.8.0 or newer)': '이 펌웨어는 튜닝을 지원하지 않습니다 (pool-2.8.0 이상 필요)',
  'Step {step} of {total} · ticks {ticks}': '{total}단계 중 {step} · 눈금 {ticks}',
  'Move the slider to tick {tick}, then press Reached this position': '슬라이더를 눈금 {tick}(으)로 옮긴 뒤 이 위치 도달을 누르세요',
  'Hold still at tick {tick}': '눈금 {tick}에서 움직이지 마세요',
  'Samples this step': '이 단계 샘플',
  'Hold': '유지',
  'Live reading': '실시간 측정값',
  'Reached this position': '이 위치 도달',
  'Measuring the hold; wait for the countdown': '유지 측정 중입니다. 카운트다운을 기다리세요',
  'Abort recording': '녹화 중단',
  'saved to {path}': '{path}에 저장됨',
  'Proposal': '제안',
  'Before (current tuning)': '이전 (현재 튜닝)',
  'After (proposed)': '이후 (제안)',
  'Current': '현재',
  'Proposed': '제안값',
  'Applies the proposed tuning until the radio restarts; nothing is written to flash.': '라디오가 재시작할 때까지 제안 튜닝을 적용합니다. 플래시에는 기록하지 않습니다.',
  "Writes the proposed tuning to the radio's flash.": '제안 튜닝을 라디오 플래시에 기록합니다.',
  'Apply & save + measured points': '적용 및 저장 + 측정 제어점',
  'Also replaces the control points with the measured ticks and saves the calibration.': '제어점도 측정한 눈금으로 바꾸고 보정을 저장합니다.',
  'unknown (no calibration report yet)': '알 수 없음 (아직 보정 보고 없음)',
  'Other pool radios': '다른 풀 라디오',
  'none known': '알려진 것 없음',
  'Suggested': '추천',
  'none free (ids 1-6 all taken)': '빈 ID 없음 (1-6 모두 사용 중)',
  'Clash': '충돌',
  'id {id} is also held by {holder}': 'ID {id}를 {holder}도 사용 중',
  'New id': '새 ID',
  '(taken: {holder})': '(사용 중: {holder})',
  '(current)': '(현재)',
  'Assign radio id {id}': '라디오 ID {id} 지정',
  'Writes the radio id to the board over USB and reboots it; the central must not see two radios on one id.': 'USB로 보드에 라디오 ID를 기록하고 재부팅합니다. 중앙이 같은 ID의 라디오 두 대를 보면 안 됩니다.',
  'id {id} is used by {holder}: assigning it forces a clash': 'ID {id}는 {holder}가 사용 중입니다. 지정하면 충돌이 생깁니다',
  'Cue override': '큐 오버라이드',
  'Leased 1.5 s: the console keeps it alive while this is on; switch it off when done.': '1.5초 리스: 켜져 있는 동안 콘솔이 유지합니다. 끝나면 끄세요.',
  '{mode} mode': '{mode} 모드',
  'no host status yet': '호스트 상태 없음',
  'No bridge beacon heard: the plate also sends the 2-byte packet the original bridge reads. Expected today.': '브리지 비컨 수신 없음: 플레이트가 원래 브리지가 읽는 2바이트 패킷도 보냅니다. 현재는 정상입니다.',
  'A bridge answers; cues are acknowledged end to end.': '브리지가 응답합니다. 큐는 끝까지 확인 응답됩니다.',
  'POINT {p} {state}': '포인트 {p} {state}',
  'Raises a TouchDesigner cue.': 'TouchDesigner 큐를 발생시킵니다.',
  '{state} on point {point} · acknowledged {ack}': '포인트 {point} {state} · 확인 응답 {ack}',
  'yes, {ms} ms': '예, {ms} ms',
  'n/a (old bridge cannot acknowledge)': '해당 없음 (구형 브리지는 확인 응답 불가)',
  'Counters': '카운터',
  'Bridge': '브리지',
  '{mac} · last beacon {ms} ms ago · sees me: {seen}': '{mac} · 마지막 비컨 {ms} ms 전 · 이 플레이트 인식: {seen}',
  'not heard from': '수신 없음',
  'no': '아니오',
  'Monitor': '모니터',
  'Firmware & database': '펌웨어 및 DB',
  'Calibration': '보정',
  'Cue test': '큐 테스트',
  'No bridge beacon heard: the plate also sends the 2-byte packet the original bridge reads.': '브리지 비컨 수신 없음: 플레이트가 원래 브리지가 읽는 2바이트 패킷도 보냅니다.',
  'bridge sees me: {seen}': '브리지 인식: {seen}',
  'Zone plate (unconfigured)': '존 플레이트 (설정 안 됨)',
  'Zone type / point': '존 종류 / 포인트',
  '{tags} tags · {unknown} unknown · {fail} send failures': '태그 {tags} · 알 수 없음 {unknown} · 전송 실패 {fail}',
  'Messages from devices, suggestion cards, job stages and errors stay in English.': '장치 메시지, 제안 카드, 작업 단계, 오류는 영어로 표시됩니다.',
};
