// flash: see ../ko.js.
export default {
  // panels/FlashSection.js
  'flashing steps': '플래시 단계',
  'Show v{v} was already on the cube': '쇼 v{v}가 이미 큐브에 있었음',
  'Show v{v} written to NVS, read back, and reported by the cube': '쇼 v{v}를 NVS에 쓰고 다시 읽었으며 큐브가 보고함',
  'The cube holds show v{v}, newer than the published one; kept': '큐브에 게시된 쇼보다 새로운 쇼 v{v}가 있어 유지함',
  'Firmware too old to hold a show; the built-in show is kept': '펌웨어가 너무 오래되어 쇼를 저장할 수 없음. 내장 쇼 유지',
  'Cube #{number}': '큐브 #{number}',
  'The cube': '큐브',
  'Switch on, then plug in a cube over USB': '켠 다음 큐브를 USB로 연결하세요',
  '{who} is up to date. Unplug it and plug in the next cube.': '{who} 최신 상태입니다. 뽑고 다음 큐브를 꽂으세요.',
  '{who}: checking the show in its storage…': '{who}: 저장소의 쇼 확인 중…',
  '{who}: firmware… keep it plugged in': '{who}: 펌웨어 쓰는 중… 뽑지 마세요',
  '{version} written and verified': '{version} 쓰기 및 검증됨',
  '{version} already on this cube': '{version} 이미 이 큐브에 있음',
  'No published show on this computer; the built-in show is kept': '이 컴퓨터에 게시된 쇼가 없음. 내장 쇼 유지',
  'written': '씀',
  'already current': '이미 최신',
  'Flash cubes': '큐브 플래시',
  'Plug in → firmware → show, over USB': '연결 → 펌웨어 → 쇼 (USB)',
  'Firmware build not ready': '펌웨어 빌드 준비 안 됨',
  'Firmware {version}': '펌웨어 {version}',
  'Show v{v}': '쇼 v{v}',
  'No published show': '게시된 쇼 없음',
  'Flash cubes as they are plugged in': '꽂는 대로 큐브 플래시',
  'Every cube on USB, now or plugged in later, gets the firmware (skipped if it already has this build) and the published show, once per plug-in.': 'USB에 있는 모든 큐브(지금 꽂혀 있거나 나중에 꽂는 큐브)가 꽂을 때마다 한 번씩 펌웨어(이미 이 빌드면 건너뜀)와 게시된 쇼를 받습니다.',
  'Off: plugging in a cube does nothing here. It is off every time the console starts.': '꺼짐: 큐브를 꽂아도 여기서는 아무것도 하지 않습니다. 콘솔을 시작할 때마다 꺼져 있습니다.',
  'The cube firmware build is not ready': '큐브 펌웨어 빌드가 준비되지 않음',
  'MAC not read yet': 'MAC 아직 읽지 않음',
  'Starting': '시작 중',
  'Retry (rewrite the firmware)': '재시도 (펌웨어 다시 쓰기)',

  // panels/RegisterSection.js (shared with FlashSection: 'Plug in a cube over USB', 'This session', 'Number')
  'Number': '번호',
  'NFC scan': 'NFC 스캔',
  'Sync': '동기화',
  'registration steps': '등록 단계',
  'Plug in a cube over USB': '큐브를 USB로 연결하세요',
  'Cube #{number} registered and synced. Unplug it and plug in the next cube.': '큐브 #{number} 등록 및 동기화 완료. 뽑고 다음 큐브를 꽂으세요.',
  'Cube #{number} is flashing: hold its NFC tag on the pairing station reader': '큐브 #{number} 점멸 중: NFC 태그를 등록 스테이션 리더에 대세요',
  'Syncing…': '동기화 중…',
  'Working…': '처리 중…',
  "NEW NUMBER: write #{number} on the cube's label": '새 번호: 큐브 라벨에 #{number}를 적으세요',
  'Number from the label': '라벨의 번호',
  'This cube already had number #{number}': '이 큐브는 이미 번호 #{number}가 있었음',
  'Label says': '라벨 번호',
  'This session': '이번 세션',
  'New': '신규',
  'new': '신규',
  'No pairing station': '등록 스테이션 없음',
  'Station connecting': '스테이션 연결 중',
  'Station ready · NFC ok': '스테이션 준비됨 · NFC 정상',
  'Station connected · NFC reader not ready': '스테이션 연결됨 · NFC 리더 준비 안 됨',
  'Register cubes': '큐브 등록',
  'Plug in → number → scan the tag → sync': '연결 → 번호 → 태그 스캔 → 동기화',
  'Register cubes as they are plugged in': '꽂는 대로 큐브 등록',
  'Plug in a cube over USB; it is taken through number, tag scan and sync.': '큐브를 USB로 연결하면 번호, 태그 스캔, 동기화를 차례로 진행합니다.',
  'Off: plugging in a cube does nothing here. Switch on to start; a cube already plugged in is registered straight away.': '꺼짐: 큐브를 꽂아도 여기서는 아무것도 하지 않습니다. 켜면 시작되며, 이미 꽂혀 있는 큐브는 바로 등록됩니다.',
  'unplugged': '뽑힘',
  'The cube printed REGISTERED over USB': '큐브가 USB로 REGISTERED를 출력함',
  'cube confirmed #{number} over USB': '큐브가 USB로 #{number} 확인',
  'Sync: {summary}': '동기화: {summary}',
  'Zones learn the tag once they hold the published database: automatic zone updates bring it to zones in range (Update all is the manual path).': '존은 게시된 데이터베이스를 받아야 태그를 인식합니다: 자동 존 업데이트가 범위 안의 존에 전달합니다 (수동은 Update all).',
  'Sync again': '다시 동기화',
  'Retry': '재시도',
  'Start again for this cube': '이 큐브 처음부터 다시',
  'The cube is unplugged': '큐브가 뽑혀 있음',
};
