// panels: see ../ko.js.
export default {
  // components/basics.js
  'explain': '설명',
  'click to copy': '클릭하여 복사',
  'copied': '복사됨',
  'sent': '보냄',
  'delivered': '전달됨',
  'acknowledged': '확인 응답됨',
  'verified': '검증됨',
  'delivery ladder': '전달 단계',
  'Check:': '확인:',
  'Enter a whole number': '정수를 입력하세요',
  'Set': '설정',
  'Enter accepts the suggested free number {n}': 'Enter를 누르면 제안된 빈 번호 {n}을(를) 사용합니다',

  // panels/CubePanel.js
  'not reported (firmware before v1.5.0, or no "?" answer yet)': '보고 없음 (v1.5.0 이전 펌웨어이거나 아직 "?" 응답 없음)',
  'v{version} from NVS (crc {crc})': 'NVS의 v{version} (crc {crc})',
  'the built-in show (compiled into the firmware)': '내장 쇼 (펌웨어에 컴파일됨)',
  'awaiting tag': '태그 대기',
  'saved, not sent': '저장됨 · 미전송',
  'unconfirmed': '미확인',
  'needs a number': '번호 필요',
  'pending': '대기 중',
  'discovered': '발견됨',
  'not in the inventory': '인벤토리에 없음',
  'the cube acknowledged its mapping; verified would need a read-back': '큐브가 매핑을 확인 응답했습니다. 검증됨이 되려면 다시 읽어야 합니다',
  '{command}: no radio delivery': '{command}: 무선 전달 없음',
  'last command': '마지막 명령',
  '{command}: radio ACK, not yet acknowledged by the cube': '{command}: 무선 ACK, 큐브의 확인 응답은 아직 없음',
  '{status}: no acknowledgment recorded': '{status}: 기록된 확인 응답 없음',
  'nothing in flight': '진행 중인 전송 없음',
  'No pairing station connected': '연결된 등록 스테이션 없음',
  'Station not connected': '스테이션 연결 안 됨',
  'NFC reader unavailable on the station': '스테이션의 NFC 리더 사용 불가',
  'Station busy: {mode}': '스테이션 사용 중: {mode}',
  'Send saved mapping': '저장된 매핑 보내기',
  'Rename': '번호 변경',
  'Excluded (reader / base station): registration and LED actions are not offered.': '제외됨 (리더 / 기지국): 등록과 LED 작업을 제공하지 않습니다.',
  'This device needs its physical label number before it can be registered.': '등록하려면 먼저 이 장치의 실제 라벨 번호가 필요합니다.',
  'Number {n} assigned': '번호 {n} 지정됨',
  'Replace tag (scan)': '태그 교체 (스캔)',
  'Register (scan a tag)': '등록 (태그 스캔)',
  "A new scan replaces this cube's committed tag; a tag held by another device is transferred.": '새 스캔이 이 큐브의 확정 태그를 교체합니다. 다른 장치가 가진 태그는 이전됩니다.',
  'Flashes the cube and waits for a fresh NFC scan at the station.': '큐브를 점멸시키고 스테이션에서 새 NFC 스캔을 기다립니다.',
  'Transmits the saved ID/UID; no scan.': '저장된 ID/UID를 전송합니다. 스캔 없음.',
  'Flash LEDs until Stop': '중지할 때까지 LED 점멸',
  'Change number': '번호 변경',
  'Renamed to #{n}': '#{n}(으)로 변경됨',
  'auto (cube)': '자동 (큐브)',
  'LED · manually assigned': 'LED · 수동 지정',
  'Reader / base station (excluded)': '리더 / 기지국 (제외)',
  'Unregister': '등록 해제',
  "Releases the number and tags in the inventory only; the cube's firmware is not changed.": '인벤토리에서만 번호와 태그를 해제합니다. 큐브 펌웨어는 바뀌지 않습니다.',
  'Assigned number': '지정 번호',
  'Original table number': '원래 표 번호',
  'NFC scanned here': '여기서 NFC 스캔됨',
  'NFC unseen here': '여기서 NFC 스캔 안 됨',
  'Committed tag (uid)': '확정 태그 (uid)',
  'Pending tag': '대기 중 태그',
  'Source / updated': '출처 / 갱신',
  'discovery reply {n} s ago': '{n}초 전 탐색 응답',
  'no discovery reply this session': '이번 세션에 탐색 응답 없음',
  'Last command': '마지막 명령',
  'Overview': '개요',
  'Cube (no number yet)': '큐브 (아직 번호 없음)',
  'unverified': '미검증',
  'zone {n}': '존 {n}',
  'local build {v}': '로컬 빌드 {v}',
  'No "?" answer yet: the version is unverified, not current.': '아직 "?" 응답 없음: 버전은 최신이 아니라 미검증 상태입니다.',
  'Reported over USB': 'USB로 보고됨',
  'no "?" answer yet': '아직 "?" 응답 없음',
  'Cube says': '큐브 보고',
  'nothing notable': '특이 사항 없음',
  'Main show': '메인쇼',
  'Flash cube firmware': '큐브 펌웨어 플래시',
  'Update show over USB': 'USB로 쇼 업데이트',
  'Identify the cube over USB first': '먼저 USB로 큐브를 식별하세요',
  'Check boot (no reflash)': '부팅 확인 (재플래시 없음)',
  'Opens the port, reads the boot banner and records the run; nothing is written.': '포트를 열어 부팅 배너를 읽고 기록합니다. 아무것도 쓰지 않습니다.',
  'Started': '시작',
  'No flash runs recorded for this cube': '이 큐브의 플래시 기록 없음',
  'Sightings': '목격 기록',

  // panels/others.js: Mainshow controller, PoolCentral, pool test bridge, preshow bridge, range test, unknown board
  'controller ready': '컨트롤러 준비됨',
  'ch {n}': '채널 {n}',
  'Lockout / rearm': '잠금 / 재무장',
  'Controller problem': '컨트롤러 문제',
  'LED test on': 'LED 테스트 켜기',
  "Lights the controller's LED.": '컨트롤러의 LED를 켭니다.',
  'LED test off': 'LED 테스트 끄기',
  'Rewrite controller firmware': '컨트롤러 펌웨어 다시 쓰기',
  'Writes flash; a first-time full backup is taken.': '플래시에 씁니다. 처음에는 전체 백업을 먼저 받습니다.',
  'Id': 'ID',
  'Holding': '유지 중',
  'Seq': '순번',
  'Lease': '리스',
  'Legacy': '구형',
  'legacy packet': '구형 패킷',
  '{n} ms ago': '{n} ms 전',
  'radio?': '무선?',
  'status {n} s ago': '{n}초 전 상태',
  'Telemetry': '원격 측정',
  'RX packets': 'RX 패킷',
  'Rejected': '거부됨',
  'Id clashes': 'ID 충돌',
  'I²C errors': 'I²C 오류',
  'Mismatches': '불일치',
  'Recoveries': '복구',
  'Log drops': '로그 누락',
  'Desired': '요청',
  'Verified': '검증됨',
  'Known': '알려짐',
  'Boards': '보드',
  'online': '온라인',
  'OFFLINE': '오프라인',
  'Recover I²C': 'I²C 복구',
  'Re-initialises both PCA9685 boards.': 'PCA9685 보드 두 개를 다시 초기화합니다.',
  'Radios': '라디오',
  'No radios heard': '수신된 라디오 없음',
  'Pool light test bridge': '풀 조명 테스트 브리지',
  'ready · channel {n}': '준비됨 · 채널 {n}',
  'not ready': '준비 안 됨',
  'This bridge emulates pool radios 1-6': '이 브리지는 풀 라디오 1-6을 에뮬레이션합니다',
  'Power off the real pool radios before testing; the central will hear this bridge instead.': '테스트 전에 실제 풀 라디오의 전원을 끄세요. 중앙 컨트롤러는 대신 이 브리지를 듣게 됩니다.',
  'RADIO SLOTS': '라디오 슬롯',
  'ALL OFF (Esc)': '모두 끄기 (Esc)',
  'Stop sequential test': '순차 테스트 중지',
  'Sequential test': '순차 테스트',
  'Lights each member in turn.': '각 멤버를 차례로 켭니다.',
  'seconds per light': '조명당 초',
  'channel': '채널',
  'Apply channel': '채널 적용',
  'Refused while any light is on.': '조명이 하나라도 켜져 있으면 거부됩니다.',
  '{mac} · queued {queued} · errors {errors}': '{mac} · 대기 {queued} · 오류 {errors}',
  '{mac} · beacon {ms} ms · radio mask {mask}': '{mac} · 비컨 {ms} ms · 라디오 마스크 {mask}',
  'no beacon heard': '수신된 비컨 없음',
  'Preshow media bridge (TouchDesigner)': '프리쇼 미디어 브리지 (TouchDesigner)',
  'bridge': '브리지',
  'Points': '포인트',
  'Plate': '플레이트',
  'No point status yet': '아직 포인트 상태 없음',
  'Plates': '플레이트',
  'No plates heard': '수신된 플레이트 없음',
  'TEST {n} ON': '테스트 {n} 켜기',
  'Writes PRESHOW,n,ON to TouchDesigner.': 'TouchDesigner에 PRESHOW,n,ON을 씁니다.',
  '{n} OFF': '{n} 끄기',
  'Recent cues': '최근 큐',
  'Range test {role}': '거리 테스트 {role}',
  'nothing written to disk': '디스크에 기록하지 않음',
  'Loss %': '손실 %',
  'RSSI avg': 'RSSI 평균',
  'Noise floor': '노이즈 플로어',
  'Packets': '패킷',
  'Span': '범위',
  'last minute': '최근 1분',
  'last 30 min': '최근 30분',
  'RSSI (dBm)': 'RSSI (dBm)',
  'loss %': '손실 %',
  "The board's own 8-LED comet, mirrored. Red = this receiver, blue = the transmitter.": '보드 자체의 8-LED 혜성 표시를 그대로 보여줍니다. 빨강 = 이 수신기, 파랑 = 송신기.',
  'Marks:': '표시:',
  'none (send MARK <label> in the console)': '없음 (콘솔에서 MARK <label> 전송)',
  'Unidentified USB board': '식별되지 않은 USB 보드',
  'What the probe saw': '탐지 결과',
  'serial {serial}': '시리얼 {serial}',
  'native ESP32 USB': 'ESP32 내장 USB',
  'adapter': '어댑터',
  'Candidate ESP32': 'ESP32 후보',
  'no (not flashable)': '아니오 (플래시 불가)',
  'Attempts': '시도',
  'Bootloader detection': '부트로더 감지',
  'not read': '읽지 않음',
  'no answer on serial': '시리얼 응답 없음',
  'Probe again (no reset)': '다시 탐지 (리셋 없음)',
  'Reboots the board.': '보드를 재부팅합니다.',
  'Read zone report': '존 보고 읽기',
  'Opens the port and sends ?': '포트를 열고 ?를 보냅니다',
  'Make this board a…': '이 보드를 다음으로 만들기…',
  'Workstation: pairing reader + zone relay + cube colours + show + pool lamp + preshow cue': 'Workstation: 등록 리더 + 존 릴레이 + 큐브 색 + 쇼 + 풀 조명 + 프리쇼 큐',
  'Neocore cube': 'Neocore 큐브',
  'For a zone plate, open the zone identity form: Read zone report first, then the Firmware & database tab appears once the board is identified as a zone. Unidentified boards can also be flashed from the zone form after "Identify via bootloader".': '존 플레이트는 존 신원 양식을 여세요: 먼저 존 보고 읽기를 하면, 보드가 존으로 식별된 뒤 Firmware & database 탭이 나타납니다. 식별되지 않은 보드도 "Identify via bootloader" 후 존 양식에서 플래시할 수 있습니다.',

  // panels/others.js: This computer, USB intake, firmware builds
  'Automatic intake': '자동 인테이크',
  'Cubes are flashed from the Flash page: firmware and the published show': '큐브는 플래시 페이지에서 플래시합니다: 펌웨어와 게시된 쇼',
  'Flash cubes · ON (Flash page)': '큐브 플래시 · 켜짐 (플래시 페이지)',
  'Flash cubes → Flash page': '큐브 플래시 → 플래시 페이지',
  'Auto-flash zones · ON': '존 자동 플래시 · 켜짐',
  'Auto-flash zones': '존 자동 플래시',
  'Identified zone boards are updated in place; legacy sketches take the zone and point below. Cubes and stations are skipped.': '식별된 존 보드는 그대로 업데이트되며, 구형 스케치는 아래의 존과 포인트를 받습니다. 큐브와 스테이션은 건너뜁니다.',
  'Armed · writing {ports}': '활성화됨 · {ports} 쓰는 중',
  'Armed · waiting for the next board': '활성화됨 · 다음 보드 대기 중',
  'Off (the default at every launch)': '꺼짐 (실행할 때마다 기본값)',
  'Zone (legacy sketches)': '존 (구형 스케치)',
  'Next point': '다음 포인트',
  'advance the point after each legacy flash': '구형 플래시마다 포인트를 다음으로 넘김',
  'include unidentified boards (bootloader read only)': '식별되지 않은 보드 포함 (부트로더 읽기만)',
  'database-only update for zones that are behind': '뒤처진 존은 데이터베이스만 업데이트',
  'Stopping either switch lets the write in progress finish; a job is never interrupted mid-flash.': '어느 스위치를 꺼도 진행 중인 쓰기는 끝까지 마칩니다. 플래시 도중에 작업을 중단하지 않습니다.',
  'Last results': '마지막 결과',
  'USB intake': 'USB 인테이크',
  'Rescan USB': 'USB 다시 검색',
  "Boards are identified automatically without resetting them. Flash from each board's panel, or arm the automatic intake below.": '보드는 리셋 없이 자동으로 식별됩니다. 각 보드 패널에서 플래시하거나 아래 자동 인테이크를 켜세요.',
  'Firmware builds': '펌웨어 빌드',
  'Target': '대상',
  'rebuild': '다시 빌드',
  'manifest and hashes verified': '매니페스트와 해시 검증됨',
  'Build': '빌드',
  'not checked yet': '아직 확인 안 함',
  'ok ({text})': '정상 ({text})',
  'PROBLEM: {text}': '문제: {text}',
  'not found (builds unavailable; flashing verified builds still works)': '찾을 수 없음 (빌드 불가, 검증된 빌드 플래시는 가능)',
  'installed': '설치됨',
  'missing': '없음',
  'Check flashing tool': '플래시 도구 확인',
  'Re-verify manifests': '매니페스트 다시 검증',
  'Other apps on this database': '이 데이터베이스의 다른 앱',
  'Held by another process: {apps} — web downloads wait while those apps run.': '다른 프로세스가 보유 중: {apps} — 해당 앱이 실행되는 동안 웹 다운로드는 대기합니다.',
  'No old app holds a lock; the console holds them all while it runs.': '잠금을 가진 이전 앱이 없습니다. 콘솔이 실행 중에는 모든 잠금을 보유합니다.',
};
