// sections: see ../ko.js.
export default {
  // panels/InventorySection.js
  'Tag': '태그',
  'pending {uid}': '대기 {uid}',
  'Original': '원래 번호',
  'Radio': '무선',
  'Role': '역할',
  'USB firmware': 'USB 펌웨어',
  'on USB': 'USB 연결됨',
  'Updated': '수정 시각',
  'filter': '필터',
  'Search inventory': '인벤토리 검색',
  'search inventory': '인벤토리 검색',
  'Grid view': '그리드 보기',
  'Table view': '표 보기',
  '{n} shown': '{n}개 표시',
  'Transmit original 32': '원래 32개 전송',
  'Sends each original mapping to its cube; refuses changed originals.': '각 원래 매핑을 해당 큐브에 보냅니다. 변경된 원래 매핑은 거부합니다.',
  'Retry unconfirmed': '미확인 재시도',
  'Retransmits every unconfirmed saved registration.': '확인되지 않은 저장 등록을 모두 다시 전송합니다.',
  'Flash all shown (2 s each)': '표시된 전체 점멸 (각 2초)',
  'Stop': '정지',
  'No devices match': '일치하는 장치 없음',
  'heard': '수신됨',
  'Device without a number': '번호 없는 장치',
  'Open USB panel →': 'USB 패널 열기 →',
  'History & sightings': '기록 및 관측',
  'Written {path}': '저장됨: {path}',
  'Export': '내보내기',
  'File path on this computer': '이 컴퓨터의 파일 경로',
  '/path/to/devices.csv or CubeTable.h': '/path/to/devices.csv 또는 CubeTable.h',
  'Reader table header': '리더 테이블 헤더',
  'Close': '닫기',
  'data/devices.csv is refreshed automatically after every change.': 'data/devices.csv는 변경할 때마다 자동으로 갱신됩니다.',
  'Type': '종류',
  'Last seen': '마지막 관측',
  'Published zone database': '게시된 존 데이터베이스',
  'Version': '버전',
  'v{version} · {count} records · CRC {crc}': 'v{version} · 레코드 {count}개 · CRC {crc}',
  'nothing published yet': '아직 게시된 것 없음',
  '{at} by {who}': '{at} · {who}',
  'Universal version': '공통 버전',
  'yes (web-allocated)': '예 (웹 할당)',
  'legacy local counter': '구형 로컬 카운터',
  'This computer': '이 컴퓨터',
  'local mappings differ from the published image — Sync publishes a new version': '로컬 매핑이 게시본과 다름 — Sync가 새 버전을 게시합니다',
  'matches the published image': '게시본과 일치',
  'Problem': '문제',
  'Sync (inventory + zone DB)': 'Sync (인벤토리 + 존 DB)',
  'Publish (allocates the next universal version)': '게시 (다음 공통 버전 할당)',
  'Pull from the web': '웹에서 가져오기',
  'What each zone holds': '각 존이 보유한 버전',
  'No zones recorded yet': '기록된 존 없음',
  'Web inventory': '웹 인벤토리',
  'To upload': '업로드 예정',
  '{n} inventory changes + zone database': '인벤토리 변경 {n}건 + 존 데이터베이스',
  '{n} inventory changes': '인벤토리 변경 {n}건',
  'To download': '다운로드 예정',
  '{n} web changes + zone database v{version}': '웹 변경 {n}건 + 존 데이터베이스 v{version}',
  '{n} web changes': '웹 변경 {n}건',
  'Waiting': '대기 중',
  '{n} downloaded changes wait for the apps to be idle': '다운로드한 변경 {n}건이 앱 유휴 상태를 기다림',
  'Lost': '밀림',
  '{n} local devices would give way to a newer change': '로컬 장치 {n}개가 더 최신 변경에 밀림',
  'Web zone DB': '웹 존 DB',
  'Checked': '확인 시각',
  'not yet': '아직 없음',
  'Password': '비밀번호',
  'stored on this computer': '이 컴퓨터에 저장됨',
  'not entered (click Sync in the top bar)': '입력 안 됨 (상단의 Sync 클릭)',
  'Sync now': '지금 Sync',
  'Check': '확인',
  'Compare this computer, the web and the baseline without writing: the record-by-record plan of the next Sync.': '쓰지 않고 이 컴퓨터, 웹, 기준본을 비교합니다: 다음 Sync의 레코드별 계획.',
  'Sign in first (Sync in the top bar)': '먼저 로그인하세요 (상단의 Sync)',
  'Refresh status': '상태 새로고침',
  'Upload only': '업로드만',
  'Download only': '다운로드만',
  'Publish zone DB': '존 DB 게시',
  'Pull zone DB': '존 DB 가져오기',
  'Forget password': '비밀번호 삭제',
  'A newer change elsewhere took priority': '다른 곳의 더 최신 변경이 우선함',
  'Sync never asks for a decision: the newest change to a device wins and every decision is audited (sync_resolved). Records are never deleted.': 'Sync는 결정을 묻지 않습니다: 장치별 가장 최신 변경이 이기고 모든 결정은 감사 기록됩니다(sync_resolved). 레코드는 삭제되지 않습니다.',
  'no tag': '태그 없음',
  'no number': '번호 없음',
  'upload + download': '업로드 + 다운로드',
  'upload': '업로드',
  'download': '다운로드',
  'Change': '변경',
  'Web': '웹',
  'After': '이후',
  'Decided': '결정',
  'newest wins': '최신 우선',
  'Both sides changed this device; the newer change takes the number and tags whole (audited as sync_resolved).': '양쪽에서 이 장치를 변경했습니다. 더 최신 변경이 번호와 태그를 통째로 가져갑니다(sync_resolved로 감사 기록).',
  'What a Sync would move': 'Sync가 옮길 내용',
  'checked {time}': '확인 {time}',
  'web revision {n}': '웹 리비전 {n}',
  'Clear': '지우기',
  'Lost locally': '로컬에서 밀림',
  'Local devices that would give way to a newer change': '더 최신 변경에 밀릴 로컬 장치',
  'Nothing would move: this computer and the web agree': '옮길 것 없음: 이 컴퓨터와 웹이 일치',
  'Recent audit events': '최근 감사 이벤트',
  'Action': '동작',
  'Detail': '상세',
  'No events': '이벤트 없음',
  'Inventory & database': '인벤토리 & 데이터베이스',
  'Every cube and zone this computer knows about, the published zone database and the web copy.': '이 컴퓨터가 아는 모든 큐브와 존, 게시된 존 데이터베이스와 웹 사본.',
  'Zone database': '존 데이터베이스',
  'Web sync': '웹 동기화',
  'Flash runs': '플래시 기록',
  'Events': '이벤트',

  // panels/ShowSection.js
  'from this app': '이 앱에서',
  'by the BOOT button': 'BOOT 버튼으로',
  'by the trigger input': '트리거 입력으로',
  'by {source}': '{source}(으)로',
  'no controller connected': '연결된 컨트롤러 없음',
  'waiting for the controller to answer {cmd}': '컨트롤러의 {cmd} 응답 대기 중',
  'nothing sent from this computer yet': '이 컴퓨터에서 아직 보낸 것 없음',
  '{text} · the cube reports nothing about the show': '{text} · 큐브는 쇼에 대해 보고하지 않음',
  'controller': '컨트롤러',
  'wrong firmware': '잘못된 펌웨어',
  'not answering': '응답 없음',
  '{name} on {port} · {state}': '{name} ({port}) · {state}',
  '{name} · {state}': '{name} · {state}',
  'none connected': '연결 없음',
  'No Mainshow controller connected': '연결된 Mainshow 컨트롤러 없음',
  'Plug in the controller board (or make a spare dongle one from its panel).': '컨트롤러 보드를 연결하세요 (또는 예비 동글의 패널에서 컨트롤러로 만드세요).',
  'Controller': '컨트롤러',
  'Cube #': '큐브 #',
  'e.g. 44': '예: 44',
  'No cube #{n} in the inventory': '인벤토리에 큐브 #{n} 없음',
  "Enter the number on the cube's label": '큐브 라벨의 번호를 입력하세요',
  '① Mainshow ready': '① 메인쇼 준비',
  'SET_ZONE 4: the cube turns neon and becomes eligible for the show.': 'SET_ZONE 4: 큐브가 네온으로 바뀌고 쇼에 참여할 수 있게 됩니다.',
  '② Trigger mainshow': '② 메인쇼 시작',
  'Fresh showId ×5 to this cube; only a mainshow-ready cube starts.': '이 큐브에 새 showId ×5 전송. 메인쇼 준비된 큐브만 시작합니다.',
  '② Trigger all ready cubes': '② 준비된 모든 큐브 시작',
  'Broadcast, no acknowledgment; cannot be undone.': '브로드캐스트, 확인 응답 없음. 되돌릴 수 없습니다.',
  'Stop → idle': '정지 → 대기(idle)',
  'SET_ZONE 0 ends the show on this cube.': 'SET_ZONE 0: 이 큐브의 쇼를 끝냅니다.',
  "Delivered means the cube's radio acknowledged; the cube reports nothing about the show itself. The BOOT button and trigger input also start the show without this computer (their triggers appear in the timeline).": '전달됨은 큐브의 무선이 확인 응답했다는 뜻이며, 큐브는 쇼 자체에 대해 보고하지 않습니다. BOOT 버튼과 트리거 입력도 이 컴퓨터 없이 쇼를 시작합니다(해당 트리거는 타임라인에 표시).',
  'Show clock': '쇼 시계',
  'Show {id} · {name} · started {by}': '쇼 {id} · {name} · {by} 시작',
  'No show started from this controller yet.': '이 컨트롤러에서 아직 시작된 쇼 없음.',
  'Waiting for the controller to answer {cmd}…': '컨트롤러의 {cmd} 응답 대기 중…',
  'Show control': '쇼 제어',
  'Make a cube mainshow-ready and start the main show.': '큐브를 메인쇼 준비 상태로 만들고 메인쇼를 시작합니다.',

  // lib/table.js
  'All devices': '전체 장치',
  'Seen recently': '최근 관측',
  'Has original number and connected': '원래 번호 있음 · 연결됨',
  'Registered (ACK)': '등록됨 (ACK)',
  'Unregistered': '미등록',
  'Needs attention': '확인 필요',
  'All incl. excluded': '제외 포함 전체',
};
