// shell (top bar, tooltips, rail, status bar, timeline, attention, shared components): see ../ko.js.
export default {
  // components/actions.js
  'Needs:': '필요 조건:',
  'Unavailable:': '사용 불가:',
  'Hold: {label}': '길게 누르기: {label}',
  '{label} · ON (leased)': '{label} · 켜짐 (리스)',
  // components/Attention.js
  'Could not confirm the action': '작업을 확인할 수 없습니다',
  '{label}: done': '{label}: 완료',
  'Not run: {reason}': '실행 안 됨: {reason}',
  'dismiss': '닫기',
  'Dismiss': '닫기',
  'Dismiss this occurrence': '이번 항목만 닫기',
  'Dismiss for this device': '이 장치에 대해 닫기',
  "Don't show this rule again": '이 규칙 다시 표시 안 함',
  'What we know:': '파악된 내용:',
  'Why it matters:': '중요한 이유:',
  'What to check:': '확인할 것:',
  'Hide details': '세부 정보 숨기기',
  'Details': '세부 정보',
  'rule {rule} · id {id}': '규칙 {rule} · id {id}',
  'attention': '주의',
  'Attention · {n}': '주의 · {n}',
  'Nothing needs attention.': '주의가 필요한 항목이 없습니다.',
  'Show fewer': '간단히 보기',
  '{n} more': '{n}개 더 보기',
  'jobs': '작업',
  'Jobs': '작업',
  '{n} running': '{n}개 실행 중',
  'No jobs yet.': '아직 작업이 없습니다.',
  // components/StatusBar.js
  'Backend not responding': '백엔드 응답 없음',
  'Connected': '연결됨',
  'Connecting…': '연결 중…',
  'not connected': '연결 안 됨',
  'no NFC': 'NFC 없음',
  'status': '상태',
  'Simulation': '시뮬레이션',
  'Fake boards on a temporary copy of the database': '데이터베이스 임시 사본에서 가상 보드로 실행 중',
  'Zone DB': '존 DB',
  'unpublished mappings': '미게시 매핑',
  'published zone database': '게시된 존 데이터베이스',
  '{total} · {registered} registered': '{total} · 등록 {registered}',
  'Station': '스테이션',
  'idle': '대기',
  // components/Timeline.js
  'Timeline': '타임라인',
  'All': '전체',
  'Log': '로그',
  'Device events': '장치 이벤트',
  'Resolved': '해결됨',
  'Warnings': '경고',
  'Errors': '오류',
  'This device': '이 장치',
  'Export…': '내보내기…',
  'No timeline events since the console opened.': '콘솔을 연 뒤 타임라인 이벤트가 없습니다.',
  // components/canvas.js
  'LED ring = last commanded colour': 'LED 링 = 마지막으로 명령한 색',
  'LED ring {label} {sub}': 'LED 링 {label} {sub}',
  'No data yet': '아직 데이터 없음',
  'ON': '켜짐',
  'OFF': '꺼짐',
  // components/data.js
  'Nothing to show': '표시할 항목 없음',
  '{n} more rows (narrow the filter)': '{n}개 행 더 있음 (필터를 좁히세요)',
  'Nothing yet': '아직 없음',
  '{n} new lines ↓': '새 줄 {n}개 ↓',
  'Filter lines': '줄 필터',
  'Send a line (e.g. {example})': '한 줄 보내기 (예: {example})',
  'Send': '보내기',
  'Log ({n})': '로그 ({n})',
  'Cancel': '취소',
  'Port': '포트',
  'Identified as': '식별 결과',
  'Inventory says': '인벤토리 기록',
  'Note': '메모',
  'No USB serial devices': 'USB 시리얼 장치 없음',
  // components/Rail.js
  'radio': '무선',
  '📌 USB pinned': '📌 USB 고정',
  'devices': '장치',
  'No devices match.': '일치하는 장치가 없습니다.',
  // lib/ladder.js
  'not yet acknowledged by the device': '장치의 확인 응답 아직 없음',
  'no delivery confirmation': '전달 확인 없음',
  // app.js
  'Not attached': '연결되지 않음',
  '{device} is not on USB right now.': '{device}이(가) 지금 USB에 연결되어 있지 않습니다.',
  'Back to devices': '장치 목록으로',
  // components/TopBar.js
  'Dark theme': '어두운 테마',
  'Light theme': '밝은 테마',
  'Match the system theme': '시스템 테마 따르기',
  'theme': '테마',
  'Devices': '장치',
  'Register': '등록',
  'Flash': '플래시',
  'Bench': '벤치',
  'Sync started': 'Sync 시작됨',
  'Checking the password…': '비밀번호 확인 중…',
  '⟳ Syncing…': '⟳ Sync 중…',
  'Web inventory password (stored on this computer, never in git)': '웹 인벤토리 비밀번호 (이 컴퓨터에만 저장, git에는 저장하지 않음)',
  'Sign in': '로그인',
  'Search  /  number, MAC, UID': '검색  /  번호, MAC, UID',
  '■ Stop': '■ 정지',
  'Stop every active operation (Esc)': '진행 중인 모든 작업 정지 (Esc)',
  'attention and jobs': '주의 및 작업',
  'Attention': '주의',
  'timeline': '타임라인',
  'settings (?)': '설정 (?)',
  'settings': '설정',
  // components/AutoUpdates.js
  'queued': '대기열',
  'building': '빌드 중',
  'failed': '실패',
  'no build tools': '빌드 도구 없음',
  'upgrading': '업그레이드 중',
  'waiting': '기다리는 중',
  'checking': '확인 중',
  'needs build': '빌드 필요',
  'skipped': '건너뜀',
  'paused': '일시 정지됨',
  'by hand': '수동으로',
  'Zone databases': '존 데이터베이스',
  'v{version}: {current} current · {behind} behind · {updating} updating': 'v{version}: 최신 {current} · 구버전 {behind} · 업데이트 중 {updating}',
  'Over-the-air zone updates are off (Settings › Automatic updates)': '무선 존 업데이트가 꺼져 있습니다 (설정 › 자동 업데이트)',
  'v{version}: {current} current · {behind} behind': 'v{version}: 최신 {current} · 구버전 {behind}',
  '{n} heard over the air in the last day with older firmware: plug in over USB to upgrade': '최근 하루 동안 무선으로 이전 펌웨어가 {n}개 확인됨: USB로 꽂아 업그레이드하세요',
  '{n} more behind, out of range: updated when a radio next hears them': '범위 밖의 구버전 {n}개 더: 다음에 무선이 들으면 업데이트됨',
  'Paused': '일시 정지됨',
  'Working': '진행 중',
  'Resume': '재개',
  'Pause': '일시 정지',
  '✓ Everything up to date': '✓ 모두 최신',
  'Build {label}': '{label} 빌드',
  '{n} to upgrade by hand': '수동 업그레이드 필요 {n}개',
  'Recent ({n})': '최근 ({n})',
};
