// show: see ../ko.js.
export default {
  // panels/ShowEditor.js: cue types and their help
  'solid': '단색',
  'fade': '페이드',
  'blink': '깜박임',
  'pulse': '펄스',
  'cycle': '순환',
  'random': '랜덤',
  'LEDs off.': 'LED 꺼짐.',
  'One steady colour.': '한 가지 색을 유지합니다.',
  'From the first colour to the second over the fade time, then holds the second.': '페이드 시간 동안 첫 번째 색에서 두 번째 색으로 바뀐 뒤 두 번째 색을 유지합니다.',
  'First colour for the on time of every period, the second colour for the rest.': '매 주기의 켜짐 시간 동안 첫 번째 색, 나머지 시간은 두 번째 색입니다.',
  'Up from the first colour to the second, then back down; holds the first after.': '첫 번째 색에서 두 번째 색으로 올라갔다가 다시 내려오며, 이후 첫 번째 색을 유지합니다.',
  'Crossfades through the colours in a loop, one step time per colour.': '색마다 한 단계 시간씩 반복하며 크로스페이드합니다.',
  'A random walk of brightness (level × the colour / 100); every cube moves differently.': '밝기가 무작위로 변합니다(레벨 × 색 / 100). 큐브마다 다르게 움직입니다.',
  // cue parameters
  'Fade time': '페이드 시간',
  'Period': '주기',
  'On time': '켜짐 시간',
  'Up time': '올라가는 시간',
  'Down time': '내려가는 시간',
  'Step time': '단계 시간',
  'Level min': '최소 레벨',
  'Level max': '최대 레벨',
  'Shortest step': '가장 짧은 단계',
  'Longest step': '가장 긴 단계',
  'Start level': '시작 레벨',
  // timeline and overview
  'fan': '패닝',
  'show timeline: ruler and colour band (rows: cubes {cubes}) scrub the playhead; cue blocks below: click to select, drag to move, drag an edge to move a start, double-click to add a cue; Ctrl or Cmd + wheel zooms':
    '쇼 타임라인: 눈금자와 색 띠(행: 큐브 {cubes})로 재생 위치 이동, 아래 큐 블록: 클릭 선택, 끌어 이동, 가장자리를 끌어 시작 이동, 더블클릭으로 큐 추가, Ctrl 또는 Cmd + 휠로 확대/축소',
  "Whole show: drag the window's edges to zoom, drag it (or click) to scroll, double-click to fit": '쇼 전체: 창 가장자리를 끌어 확대/축소, 창을 끌거나 클릭해 이동, 더블클릭으로 전체 맞춤',
  "whole-show overview: drag the window's left or right edge to zoom, drag inside it or click to move the view, double-click to fit the whole show":
    '쇼 전체 개요: 창의 왼쪽 또는 오른쪽 가장자리를 끌어 확대/축소, 창 안을 끌거나 클릭해 보기 이동, 더블클릭으로 쇼 전체 맞춤',
  // cue inspector
  '{label} colour': '{label} 색',
  '{c} level 0-100 (the cube caps LEDs at 100)': '{c} 레벨 0-100 (큐브의 LED 최대값은 100)',
  'Time is m:ss.mmm': '시간 형식은 m:ss.mmm입니다',
  'Select a cue in the lane below the colour band.': '색 띠 아래 레인에서 큐를 선택하세요.',
  'From': '시작 색',
  'To': '끝 색',
  'On': '켜짐',
  'Off': '꺼짐',
  'Cue {n}': '큐 {n}',
  'label': '이름',
  'cue type': '큐 종류',
  'Start': '시작',
  'ends {end} · lasts {secs} s': '종료 {end} · 길이 {secs}초',
  'Colour {n}': '색 {n}',
  '+ colour': '+ 색',
  '− colour': '− 색',
  // fanning
  'Fanning': '패닝',
  'per-cube offset by cube number': '큐브 번호에 따른 큐브별 오프셋',
  'Fan': '패닝',
  'fan mode': '패닝 방식',
  'none: every cube together': '없음: 모든 큐브 동시',
  'sequential: step × position in a group': '순차: 단계 × 그룹 내 위치',
  'scatter: fixed random spread': '분산: 고정된 무작위 분산',
  'Step': '단계',
  'ms per cube': '큐브당 ms',
  'Group of': '그룹 크기',
  'cubes, then it repeats': '큐브, 이후 반복',
  'Spread': '분산 폭',
  'ms: each cube gets a fixed offset in 0-spread': 'ms: 큐브마다 0-분산 폭 안의 고정 오프셋',
  'Each cube starts this cue later by its offset, holding the first colour until then.': '각 큐브는 오프셋만큼 이 큐를 늦게 시작하며, 그때까지 첫 번째 색을 유지합니다.',
  'Each cube runs this cue shifted by its offset.': '각 큐브는 오프셋만큼 밀려서 이 큐를 재생합니다.',
  'Offsets: {offsets}. A cube with no number has none. Needs cube firmware v1.6.0; an older cube refuses the whole show and keeps its current one.':
    '오프셋: {offsets}. 번호가 없는 큐브는 오프셋이 없습니다. 큐브 펌웨어 v1.6.0이 필요하며, 이전 큐브는 쇼 전체를 거부하고 현재 쇼를 유지합니다.',
  // cubes and distribution
  'show held by each cube (v0 = compiled-in default)': '각 큐브가 가진 쇼 (v0 = 내장 기본 쇼)',
  'No show relay connected': '쇼 릴레이가 연결되지 않음',
  'Updating cube shows needs a Workstation (or General Radio general-radio-1.1.0+). Publishing to the web works without one.': '큐브 쇼를 업데이트하려면 Workstation(또는 General Radio general-radio-1.1.0+)이 필요합니다. 웹 게시는 없어도 됩니다.',
  'A show is running': '쇼 진행 중',
  "Cube updates wait until the controller's show ends; a cube never switches shows mid-show.": '큐브 업데이트는 컨트롤러의 쇼가 끝날 때까지 기다립니다. 큐브는 쇼 도중 쇼를 바꾸지 않습니다.',
  'Published': '게시됨',
  '{n} bytes': '{n}바이트',
  'nothing yet': '아직 없음',
  'none heard yet (Query)': '아직 응답 없음 (Query)',
  'Auto update': '자동 업데이트',
  'on: cubes in range on an older show are updated (saved; Settings › Automatic updates)': '켜짐: 범위 안에서 이전 쇼를 가진 큐브를 업데이트 (저장됨, 설정 › 자동 업데이트)',
  'off (saved; Settings › Automatic updates)': '꺼짐 (저장됨, 설정 › 자동 업데이트)',
  '{done}/{total} confirmed · cycle {cycle} · {secs} s': '{done}/{total} 확인됨 · 회차 {cycle} · {secs}초',
  'waiting for the show to end': '쇼 종료 대기 중',
  'Query cubes': '큐브 조회',
  'Broadcast SHOW_QUERY: every v1.5.0+ cube in range answers within 2 s.': 'SHOW_QUERY 브로드캐스트: 범위 내 모든 v1.5.0+ 큐브가 2초 안에 응답합니다.',
  'Update all to v{version}': '전체를 v{version}(으)로 업데이트',
  'Update all': '전체 업데이트',
  'Broadcasts the published show until every cube heard recently confirms it. Cubes playing a show commit it when their show ends.':
    '최근 응답한 모든 큐브가 확인할 때까지 게시된 쇼를 브로드캐스트합니다. 쇼를 재생 중인 큐브는 쇼가 끝나면 적용합니다.',
  'Auto update off': '자동 업데이트 끄기',
  'Auto update on': '자동 업데이트 켜기',
  'Walk around: any cube in range on an older show is updated automatically.': '돌아다니며 업데이트: 범위 내 이전 쇼 큐브를 자동으로 업데이트합니다.',
  'Update selected ({n})': '선택 항목 업데이트 ({n})',
  'Sends the published show until the ticked cubes confirm it (other cubes in range on an older show take it too: every cube gets the same show).':
    '체크한 큐브가 확인할 때까지 게시된 쇼를 보냅니다(범위 내 이전 쇼 큐브도 함께 받습니다. 모든 큐브가 같은 쇼를 가집니다).',
  'Stop sending': '전송 중지',
  'Plugged-in': 'USB 연결 큐브',
  'While on, every cube you plug in over USB joins the selection and stays in it after you unplug it (needs a number in the inventory)': '켜져 있는 동안 USB로 연결한 큐브가 선택에 추가되고, 연결을 해제해도 선택에 남습니다 (인벤토리에 번호 필요)',
  'Added plugged-in {cubes} to the preview': 'USB 연결 큐브 {cubes}을(를) 미리보기에 추가함',
  'Send length to controller': '컨트롤러에 길이 전송',
  "show_config: the Mainshow controller (mainshow-1.3.0+) bounds its timecode by the published show's length.": 'show_config: Mainshow controller(mainshow-1.3.0+)가 게시된 쇼 길이로 타임코드 범위를 정합니다.',
  'select every cube behind': '뒤처진 큐브 모두 선택',
  'Show': '쇼',
  'Staging': '수신 중',
  'Signal': '신호',
  'Seen': '마지막 확인',
  'select {mac}': '{mac} 선택',
  'waits for show end': '쇼 종료 대기',
  'Update': '업데이트',
  'No cube has answered a show query yet.': '아직 쇼 조회에 응답한 큐브가 없습니다.',
  // reference video
  'Drop a video file (mp4, mov, webm…)': '영상 파일을 놓으세요 (mp4, mov, webm…)',
  'Play, pause, scrubbing, rate and loop drive the video. It plays from this computer and is never uploaded.': '재생, 일시정지, 이동, 속도, 반복이 영상에 적용됩니다. 이 컴퓨터에서 재생되며 업로드되지 않습니다.',
  'Drop to load the video': '놓으면 영상을 불러옵니다',
  'Reference video': '참고 영상',
  'Drag a video file here: it plays in step with the timeline, from this computer (never uploaded).': '영상 파일을 여기로 끌어 놓으세요. 이 컴퓨터에서 타임라인에 맞춰 재생됩니다(업로드되지 않음).',
  'Choose file…': '파일 선택…',
  'Drop to replace {name}': '놓으면 {name}을(를) 교체합니다',
  'Video starts at show time {time}': '영상은 쇼 시간 {time}에 시작합니다',
  "The offset puts the video's 0:00 after the show's.": '오프셋 때문에 영상의 0:00이 쇼의 0:00보다 뒤에 있습니다.',
  'Video ended': '영상 끝',
  '{time} long; the show continues.': '길이 {time}, 쇼는 계속됩니다.',
  "The show's 0:00 is at {time} in the video (remembered per file name)": '쇼의 0:00은 영상의 {time} 지점입니다 (파일 이름별로 기억)',
  'Offset': '오프셋',
  "video offset in milliseconds (the show's 0:00 in the video)": '영상 오프셋(ms, 영상에서 쇼의 0:00 위치)',
  "ms: the show's 0:00 is at {time} in the video": 'ms: 쇼의 0:00은 영상의 {time} 지점입니다',
  'Unmute': '소리 켜기',
  'Mute': '음소거',
  'Smaller': '작게',
  'Larger': '크게',
  'Choose another video file': '다른 영상 파일 선택',
  'Replace…': '교체…',
  'Remove the video': '영상 제거',
  // previewed cubes and mirroring
  'One': '하나',
  'band rows {cubes}': '색 띠 행 {cubes}',
  'previewed cubes and mirroring on the real cubes': '미리보기 큐브와 실물 큐브 미러링',
  'Preview cubes': '미리보기 큐브',
  'e.g. 1-8, 12': '예: 1-8, 12',
  'cube numbers to preview': '미리볼 큐브 번호',
  'quick cube sets': '빠른 큐브 선택',
  'Preview cube #{cubes}': '큐브 #{cubes} 미리보기',
  'Preview cubes #{cubes}': '큐브 #{cubes} 미리보기',
  'Live on {cubes}': '{cubes}에 실시간 표시 중',
  'Stop sending; each cube falls back when its last colour lapses (0.6 s)': '전송 중지. 각 큐브는 마지막 색이 만료되면(0.6초) 원래 상태로 돌아갑니다',
  'Send to real cubes {cubes}': '실물 큐브 {cubes}에 보내기',
  "While on, cubes in range whose number is previewed show the editor's colour at the playhead (playing, scrubbing or paused).":
    '켜져 있는 동안 번호가 미리보기에 있는 범위 내 큐브가 재생 위치의 편집기 색을 표시합니다(재생, 이동, 일시정지 중 모두).',
  '{n} cube previewed': '큐브 {n}개 미리보기',
  '{n} cubes previewed': '큐브 {n}개 미리보기',
  'Numbers and ranges, e.g. 1-8, 12': '번호와 범위, 예: 1-8, 12',
  'mirrored every {ms} ms (cube firmware v1.7.0-USB.1; a cube playing a real show ignores it)': '{ms} ms마다 미러링 (큐브 펌웨어 v1.7.0-USB.1, 실제 쇼를 재생 중인 큐브는 무시)',
  'Send makes those real cubes follow the playhead (cube firmware v1.7.0-USB.1)': '보내기를 누르면 해당 실물 큐브가 재생 위치를 따라갑니다 (큐브 펌웨어 v1.7.0-USB.1)',
  'mirroring needs a Workstation (or General Radio general-radio-1.2.0+) connected': '미러링하려면 Workstation(또는 General Radio general-radio-1.2.0+) 연결이 필요합니다',
  'The radio refused live colours ({error})': '라디오가 실시간 색을 거부했습니다 ({error})',
  '{firmware} cannot relay live colours: flash the Workstation firmware (or general-radio-1.2.0+).': '{firmware}은(는) 실시간 색을 중계할 수 없습니다: Workstation 펌웨어(또는 general-radio-1.2.0+)를 플래시하세요.',
  // page, transport and tools
  'go to m:ss': 'm:ss로 이동',
  'go to time (m:ss.mmm), Enter': '시간으로 이동 (m:ss.mmm), Enter',
  'Mirroring stopped: {error}': '미러링 중지됨: {error}',
  'The first cue already starts at 0:00': '첫 번째 큐는 이미 0:00에 시작합니다',
  'A cue already starts there; move the playhead': '그 위치에 이미 큐가 시작됩니다. 재생 위치를 옮기세요',
  'The first cue cannot be removed (the show starts with it)': '첫 번째 큐는 삭제할 수 없습니다 (쇼가 이 큐로 시작함)',
  'Show editor': '쇼 편집기',
  'Loading…': '불러오는 중…',
  'Fix the show before publishing': '게시하기 전에 쇼를 수정하세요',
  'Publishing the show…': '쇼 게시 중…',
  'unsaved edits': '저장 안 된 편집',
  'saved on this computer': '이 컴퓨터에 저장됨',
  'same as published v{version}': '게시된 v{version}과 같음',
  'differs from published v{version}': '게시된 v{version}과 다름',
  'not published yet': '아직 게시 안 됨',
  '{n} cues': '큐 {n}개',
  'started from {origin}': '시작 원본 {origin}',
  'image {bytes} B': '이미지 {bytes} B',
  '(the compiled-in default)': '(내장 기본 쇼)',
  'No earlier version to revert to': '되돌릴 이전 버전이 없습니다',
  'Already the same as the last version': '이미 마지막 버전과 같습니다',
  'Reverted to published v{version} (Undo brings your edits back)': '게시된 v{version}(으)로 되돌렸습니다 (실행 취소로 편집 복원)',
  'Reverted to the compiled-in default (Undo brings your edits back)': '내장 기본 쇼로 되돌렸습니다 (실행 취소로 편집 복원)',
  'Replace the working copy with published v{version}; Undo brings it back': '작업 사본을 게시된 v{version}(으)로 바꿉니다. 실행 취소로 복원됩니다',
  'Nothing published yet: replace the working copy with the compiled-in default; Undo brings it back': '아직 게시된 쇼가 없음: 작업 사본을 내장 기본 쇼로 바꿉니다. 실행 취소로 복원됩니다',
  'Revert to v{version}': 'v{version}(으)로 되돌리기',
  'Revert to default': '기본 쇼로 되돌리기',
  'Publish this show on the web as the next version (cubes are not touched)': '이 쇼를 다음 버전으로 웹에 게시합니다 (큐브는 바뀌지 않음)',
  'Publish': '게시',
  'Pull': '가져오기',
  'Fetch the published show from the web': '웹에서 게시된 쇼를 가져옵니다',
  'The main show the cubes play (cube firmware v1.5.0+). Edit, publish a version, then update the cubes over the radio.':
    '큐브가 재생하는 메인쇼(큐브 펌웨어 v1.5.0+)입니다. 편집하고 버전을 게시한 뒤 무선으로 큐브를 업데이트합니다.',
  'The cubes would refuse this show': '큐브가 이 쇼를 거부합니다',
  'Stop and return to 0:00 (Home)': '정지 후 0:00으로 (Home)',
  'Previous cue start (again within 0.25 s: the one before)': '이전 큐 시작 (0.25초 안에 다시 누르면 그 앞 큐)',
  'Pause (Space)': '일시정지 (Space)',
  'Play (Space)': '재생 (Space)',
  'Next cue start': '다음 큐 시작',
  'cue {n}': '큐 {n}',
  'ended': '끝남',
  'playback rate': '재생 속도',
  'Play at {rate}× speed': '{rate}× 속도로 재생',
  'Loop': '반복',
  'loop': '반복',
  'off: stop at the end': '끔: 끝에서 정지',
  'the selected cue': '선택한 큐',
  'the whole show': '쇼 전체',
  'Add a cue at the playhead, copying the cue it splits (or double-click the cue lane)': '재생 위치에 큐 추가, 나뉘는 큐를 복사 (또는 큐 레인 더블클릭)',
  'Delete the selected cue (Delete)': '선택한 큐 삭제 (Delete)',
  'Undo the last edit (⌘Z / Ctrl+Z)': '마지막 편집 되돌리기 (⌘Z / Ctrl+Z)',
  'Redo (⇧⌘Z / Ctrl+Y)': '다시 실행 (⇧⌘Z / Ctrl+Y)',
  'Fit the whole show in view (or double-click the overview)': '쇼 전체를 화면에 맞춤 (또는 개요 더블클릭)',
  'play': '재생',
  "Top: the whole-show overview; drag its window's edges to zoom (or Ctrl/⌘ + wheel over the timeline), drag the window to scroll, double-click it to fit. Then the ruler and the colour band (the show as cubes {cubes} play it, one row each, top to bottom; fanning offsets each by its number and random cues differ per cube; 100, the cube's cap, is full brightness). Click or drag either to scrub. Below: one block per cue with its colours on top and the cue under the playhead underlined. Click a block to select it, drag it to move it, drag its left edge to move only its start (10 ms steps), double-click to add a cue there.":
    '맨 위: 쇼 전체 개요. 창 가장자리를 끌어 확대/축소(또는 타임라인 위에서 Ctrl/⌘ + 휠), 창을 끌어 이동, 더블클릭으로 전체 맞춤. 그 아래 눈금자와 색 띠(큐브 {cubes}가 재생하는 쇼, 위에서 아래로 한 행씩. 패닝은 번호에 따라 오프셋되고 랜덤 큐는 큐브마다 다르며, 큐브 최대값 100이 최대 밝기). 둘 다 클릭하거나 끌어 재생 위치를 이동합니다. 아래: 큐마다 블록 하나, 위쪽에 큐의 색, 재생 위치의 큐에 밑줄. 블록을 클릭해 선택, 끌어 이동, 왼쪽 가장자리를 끌어 시작만 이동(10 ms 단위), 더블클릭으로 그 위치에 큐 추가.',
  'Length': '길이',
  'At the end the cube turns off and leaves mainshow-ready, as before.': '끝나면 큐브는 이전과 같이 꺼지고 메인쇼 준비 상태를 벗어납니다.',
  'Preview': '미리보기',
  'at the playhead': '재생 위치 기준',
  'show ended': '쇼 끝남',
  'mirrored on the real cubes': '실물 큐브에 미러링 중',
  '#{cube}: levels R{r} G{g} B{b}': '#{cube}: 레벨 R{r} G{g} B{b}',
  '#{cube}: show ended': '#{cube}: 쇼 끝남',
  'Working copy': '작업 사본',
  'Revert to published': '게시본으로 되돌리기',
  "Discards this computer's edits.": '이 컴퓨터의 편집을 버립니다.',
  'Start from the default': '기본 쇼에서 시작',
  "The compiled-in v1.4.1 show. Discards this computer's edits.": '내장된 v1.4.1 쇼입니다. 이 컴퓨터의 편집을 버립니다.',
  'Export JSON': 'JSON 내보내기',
  'Import JSON…': 'JSON 가져오기…',
  'Paste a show JSON (shows/mainshow.json format)': '쇼 JSON을 붙여 넣으세요 (shows/mainshow.json 형식)',
  'Replace the working copy': '작업 사본 교체',
};
