// workstation: see ../ko.js.
export default {
  // rail.js
  'Stations': '스테이션',
  'Zones': '존',
  'Cubes (live)': '큐브 (무선 수신)',
  'Unidentified USB': '미확인 USB',
  'Pairing station': '등록 스테이션',
  'ESP-NOW dongle': 'ESP-NOW 동글',
  'Unconfigured zone': '설정 안 된 존',
  'Cube (no number)': '큐브 (번호 없음)',
  'Cube {mac}': '큐브 {mac}',
  'USB device': 'USB 장치',
  'USB intake & builds': 'USB 인식 및 빌드',
  // WorkstationPanel.js: zone relay
  'Error': '오류',
  '{ago} ago': '{ago} 전',
  'Zone relay (over the air)': '존 릴레이 (무선)',
  'Relay': '릴레이',
  'station not connected or no zone support': '스테이션 미연결 또는 존 지원 없음',
  'Message': '메시지',
  '{near} in range · {out} out of range ({shown}) · {behind} behind': '범위 안 {near} · 범위 밖 {out} ({shown}) · 뒤처짐 {behind}',
  'shown': '표시',
  'hidden': '숨김',
  'Publishing v{v}': 'v{v} 게시 중',
  'cycle {cycles} · {elapsed} s · {pending} pending of {expected} · {failures} send failures': '주기 {cycles} · {elapsed}초 · {expected}개 중 {pending}개 대기 · 전송 실패 {failures}',
  'Query zones': '존 조회',
  'auto-refresh (3 s)': '자동 새로고침 (3초)',
  'Update all out-of-date zones ({n})': '오래된 존 모두 업데이트 ({n})',
  'One broadcast run for every in-range zone that is behind.': '범위 안의 뒤처진 모든 존에 브로드캐스트를 한 번 실행합니다.',
  'walkaround': '순회 업데이트',
  'auto-update all (walk the space)': '모두 자동 업데이트 (공간을 돌며)',
  'another relay is walking': '다른 릴레이가 순회 중',
  'Stop publishing': '게시 중지',
  'Show out of range ({n})': '범위 밖 표시 ({n})',
  'Every zone heard is out of range (tick Show out of range)': '수신된 모든 존이 범위 밖입니다 (범위 밖 표시를 체크하세요)',
  'No zones have answered yet': '아직 응답한 존이 없습니다',
  // discovery and cube colours
  'Cubes heard over the radio ({n})': '무선으로 수신된 큐브 ({n})',
  'No discovery replies yet. Discover runs on connection and every few seconds while idle.': '아직 검색 응답이 없습니다. 검색은 연결 시와 대기 중 몇 초마다 실행됩니다.',
  'preshow': '프리쇼',
  'desert': '사막',
  'pool': '풀',
  'mainshow': '메인쇼',
  'choose a cube…': '큐브 선택…',
  'Set {cube} → {zone}': '{cube} → {zone} 설정',
  'cube': '큐브',
  "Unicast SET_ZONE ×3; the cube's radio ACK is not a colour change.": '유니캐스트 SET_ZONE ×3. 큐브의 무선 ACK는 색 변경을 뜻하지 않습니다.',
  'Start show on this cube': '이 큐브에서 쇼 시작',
  'MSG_SHOW_START with a fresh showId ×5; only a mainshow-ready cube starts.': '새 showId로 MSG_SHOW_START ×5. 메인쇼 준비된 큐브만 시작합니다.',
  'ALL cubes in range → {zone} (hold)': '범위 안 모든 큐브 → {zone} (길게 누르기)',
  'Broadcast SET_ZONE: recolours every cube that hears it, with no acknowledgment.': '브로드캐스트 SET_ZONE: 수신한 모든 큐브의 색을 바꾸며, 확인 응답이 없습니다.',
  'Start show on ALL ready cubes (hold)': '준비된 모든 큐브에서 쇼 시작 (길게 누르기)',
  'Broadcast SHOW_START, no acknowledgment; cannot be undone.': '브로드캐스트 SHOW_START, 확인 응답 없음. 되돌릴 수 없습니다.',
  'Identify (flash until Stop)': '식별 (정지할 때까지 깜박임)',
  'The cube blinks blue/red until Stop; it is returned to idle afterwards.': '정지할 때까지 큐브가 파랑/빨강으로 깜박이고, 그 뒤 대기로 돌아갑니다.',
  'Flash 2 s': '2초 깜박임',
  'A two-second blue/red flash on the cube, then idle.': '큐브가 2초 동안 파랑/빨강으로 깜박인 뒤 대기로 돌아갑니다.',
  'Radio state': '무선 상태',
  'Shows started': '시작한 쇼',
  'Last show id': '마지막 쇼 id',
  "Show running (radio's view)": '쇼 진행 중 (무선 기준)',
  'Lockout': '잠금',
  'Colours sent:': '보낸 색:',
  "{name} → {zone}: {delivered}/{sent} frames acknowledged by the cube's radio": '{name} → {zone}: {sent}개 프레임 중 {delivered}개를 큐브 무선이 확인 응답',
  '(broadcast is never acknowledged)': '(브로드캐스트는 확인 응답되지 않음)',
  // pool lamp
  'One lamp at a time': '한 번에 램프 하나',
  'The central keys its slots by sender address, so this radio holds one member. It is released 0.6 s after this page stops holding it, and by the radio itself 1.5 s after the console stops pinging.': '센트럴은 보낸 주소별로 슬롯을 구분하므로 이 무선은 멤버 하나만 유지합니다. 이 페이지가 유지를 멈추면 0.6초 뒤, 콘솔 신호가 멈추면 무선 자체가 1.5초 뒤 해제합니다.',
  'Radio id (label at the central)': '무선 id (센트럴의 라벨)',
  'Release lamp (Esc)': '램프 해제 (Esc)',
  'member {n}': '멤버 {n}',
  'nothing': '없음',
  'Radio says': '무선 보고',
  'member {member} · radio id {id}': '멤버 {member} · 무선 id {id}',
  'released': '해제됨',
  'unicast (beacon fresh)': '유니캐스트 (비컨 최신)',
  'broadcast (no fresh beacon)': '브로드캐스트 (최신 비컨 없음)',
  'radio mask {mask}': '무선 마스크 {mask}',
  'no beacon heard yet': '아직 비컨 수신 없음',
  'Last beacon': '마지막 비컨',
  '{time} · epoch {epoch} · up {up} s · v{v}': '{time} · epoch {epoch} · 가동 {up}초 · v{v}',
  // pairing verbs
  'Pairing goes via the primary link': '등록은 주 링크를 거칩니다',
  'No NFC reader on this board': '이 보드에는 NFC 리더가 없습니다',
  'This board has a reader, but another link is the primary pairing link: the Cube panel and the pairing flows use it.': '이 보드에 리더가 있지만 다른 링크가 주 등록 링크입니다. 큐브 패널과 등록 흐름은 그 링크를 사용합니다.',
  'Discovery, identify flashes and sending saved mappings work through this board; a fresh tag scan needs the primary pairing link.': '검색, 식별 깜박임, 저장된 매핑 전송은 이 보드로 됩니다. 새 태그 스캔에는 주 등록 링크가 필요합니다.',
  "The buttons here use this board's own radio.": '여기 버튼은 이 보드 자체의 무선을 사용합니다.',
  'Discover': '검색',
  'no tag saved': '저장된 태그 없음',
  'Send saved mapping to #{n}': '#{n}에 저장된 매핑 보내기',
  "Registers the saved number and tag on the cube over the air (three attempts, then the cube's acknowledgment).": '저장된 번호와 태그를 무선으로 큐브에 등록합니다 (세 번 시도 후 큐브의 확인 응답).',
  // preshow cue
  'POINT {p} · ON → off': 'POINT {p} · ON → 끄기',
  'POINT {p} ON': 'POINT {p} ON',
  'Raises a TouchDesigner cue through the bridge; held only while this page holds it.': '브리지를 통해 TouchDesigner 큐를 올립니다. 이 페이지가 유지하는 동안만 유지됩니다.',
  'Release cue (Esc)': '큐 해제 (Esc)',
  'point {n} ON': '포인트 {n} ON',
  'point {point} {state} · seq {seq} · {ack}': '포인트 {point} {state} · seq {seq} · {ack}',
  'acknowledged in {ms} ms': '{ms} ms 만에 확인 응답',
  'not acknowledged': '확인 응답 없음',
  'modern · a bridge answers, cues are acknowledged end to end': 'modern · 브리지가 응답하며, 큐가 끝까지 확인 응답됩니다',
  'legacy · no bridge beacon heard; the 2-byte packet is also sent and nothing can acknowledge it': 'legacy · 브리지 비컨 수신 없음. 2바이트 패킷도 보내지만 아무것도 확인 응답할 수 없습니다',
  'unicast': '유니캐스트',
  'broadcast': '브로드캐스트',
  'sees me: {answer}': '이 무선 인식: {answer}',
  '{time} · epoch {epoch} · point mask {mask}': '{time} · epoch {epoch} · 포인트 마스크 {mask}',
  'Recent acks:': '최근 확인 응답:',
  '{time} point {point} {state} in {ms} ms': '{time} 포인트 {point} {state} · {ms} ms',
  // station pairing
  'Discovery, identify flashes and sending saved mappings work through this link; a fresh tag scan needs a board with a reader (a Workstation or a pairing station).': '검색, 식별 깜박임, 저장된 매핑 전송은 이 링크로 됩니다. 새 태그 스캔에는 리더가 있는 보드(Workstation 또는 등록 스테이션)가 필요합니다.',
  'Pair new cubes (auto)': '새 큐브 등록 (자동)',
  'Discovers new cubes, flashes each in turn and waits for its tag.': '새 큐브를 검색하고, 차례로 깜박이며 각 큐브의 태그를 기다립니다.',
  'Retry paused': '일시 중지된 항목 재시도',
  'Skip': '건너뛰기',
  'Recover NFC reader': 'NFC 리더 복구',
  'I²C bus clear and PN532 re-init; refused while an operation runs.': 'I²C 버스 정리 후 PN532 재초기화. 작업 중에는 거부됩니다.',
  'NFC status': 'NFC 상태',
  'Current target': '현재 대상',
  // tabs and header
  'Pairing': '등록',
  'Zone relay': '존 릴레이',
  'Cubes & show': '큐브 및 쇼',
  'Pool lamp': '풀 램프',
  'Preshow cue': '프리쇼 큐',
  'board': '보드',
  'this {who} has no zone relay (legacy pairing firmware without zone support; reflash it with nct-pairing-1.8-zones or the Workstation firmware)': '이 {who}에는 존 릴레이가 없습니다 (존 지원 없는 구형 등록 펌웨어. nct-pairing-1.8-zones 또는 Workstation 펌웨어로 다시 플래시하세요)',
  'cube-colour': '큐브 색',
  'pool-lamp': '풀 램프',
  'preshow-cue': '프리쇼 큐',
  'this {who} has no {role} role; a Workstation or General Radio does': '이 {who}에는 {role} 역할이 없습니다. Workstation 또는 General Radio에 있습니다',
  'radio ready': '무선 준비됨',
  'no session': '세션 없음',
  'no NFC reader': 'NFC 리더 없음',
  'This board relays the radio only; a fresh tag scan needs a board with a reader.': '이 보드는 무선 릴레이만 합니다. 새 태그 스캔에는 리더가 있는 보드가 필요합니다.',
  'channel {n}': '채널 {n}',
  'no zone relay': '존 릴레이 없음',
  'This firmware has no zone support; reflash it with nct-pairing-1.8-zones or the Workstation firmware.': '이 펌웨어는 존을 지원하지 않습니다. nct-pairing-1.8-zones 또는 Workstation 펌웨어로 다시 플래시하세요.',
  'host lease lapsed': '호스트 리스 만료',
  'The radio has not heard a ping within 5 s; it releases anything it held.': '무선이 5초 안에 신호를 받지 못했습니다. 유지하던 것을 모두 해제합니다.',
  'LED test': 'LED 테스트',
  'radio fault': '무선 오류',
  'carries pairing + zone relay': '등록 + 존 릴레이 담당',
  'This board is the primary pairing link: the Cube panel, the pairing flows and the zone relay go through it.': '이 보드가 주 등록 링크입니다. 큐브 패널, 등록 흐름, 존 릴레이가 이 보드를 거칩니다.',
  'pairing goes via the primary link': '등록은 주 링크 경유',
  "Another board is the primary pairing link and carries the pairing flows; this board's own verbs are on its Pairing tab.": '다른 보드가 주 등록 링크로 등록 흐름을 담당합니다. 이 보드 자체 기능은 등록 탭에 있습니다.',
  'Roles': '역할',
  '{state} · I²C status {status} · PN532 {firmware}': '{state} · I²C 상태 {status} · PN532 {firmware}',
  'unavailable': '사용 불가',
  'Tag on reader': '리더 위 태그',
  'yes (remove it before registering)': '있음 (등록 전에 치우세요)',
  'clear': '없음',
  '{sent} sent · {delivered} delivered · {unconfirmed} unconfirmed · {none} no result · {rejected} rejected': '보냄 {sent} · 전달됨 {delivered} · 미확인 {unconfirmed} · 결과 없음 {none} · 거부 {rejected}',
  '{zone} zone frames · {dropped} dropped · {overflows} serial overflows': '존 프레임 {zone} · 버림 {dropped} · 시리얼 오버플로 {overflows}',
  'Status': '상태',
  'Last disconnect': '마지막 연결 끊김',
  'Not on this board: {why}': '이 보드에서 사용 불가: {why}',
  'The radio driver stopped answering': '무선 드라이버가 응답하지 않습니다',
  'Radio problem': '무선 문제',
  'Every radio operation is refused until the board is power-cycled; its own leases release anything it held. Unplug and replug it, then probe again.': '보드 전원을 껐다 켤 때까지 모든 무선 작업이 거부됩니다. 보드 자체 리스가 유지하던 것을 해제합니다. 뽑았다 다시 꽂은 뒤 다시 확인하세요.',
  'The primary link carries the zone relay: the table below is its view, the buttons send through this board.': '존 릴레이는 주 링크가 담당합니다. 아래 표는 그 링크의 보기이고, 버튼은 이 보드로 보냅니다.',
  // console tab and ladder
  "Cycles the board's eight WS2812s.": '보드의 WS2812 8개를 순환 점등합니다.',
  'Release everything': '모두 해제',
  'Station events (JSON)': '스테이션 이벤트 (JSON)',
  'no registration in flight': '진행 중인 등록 없음',
  'flashing the cube, waiting for a fresh tag': '큐브 깜박이는 중, 새 태그 대기',
  'radio ACK; waiting for the cube to acknowledge the mapping': '무선 ACK. 큐브의 매핑 확인 응답 대기 중',
  'mapping sent over the radio': '매핑을 무선으로 보냄',
  'the cube acknowledged; remove the tag': '큐브가 확인 응답함. 태그를 치우세요',
  'no acknowledgment: Retry or Skip': '확인 응답 없음: 재시도 또는 건너뛰기',
  'identify': '식별',
};
