"""Operator-facing explanations and the status vocabulary, in Python so tests can check coverage.

TONES: ok / warn / bad / info / muted, always shown with a glyph as well as a colour.
PANELS: what a panel does and what to check. STATUS: label, tone and a tooltip per status key.
ACTIONS: labels and hazard text per command. LADDER: the truth ladder every outcome uses.
"""
TONES = ('ok', 'warn', 'bad', 'info', 'muted')
GLYPHS = dict(ok='●', warn='▲', bad='✕', info='◐', muted='○')
LADDER = {'sent': 'Sent from this computer', 'delivered': 'Delivered to the radio or written (no application acknowledgment)',
          'acknowledged': 'Acknowledged by the device', 'verified': 'Read back and verified', 'failed': 'Failed'}

PANELS = {
    'devices': dict(title='Devices', what='Everything on USB and everything heard over the radio, grouped by role.',
                    check='A grey radio dot means no discovery reply this session, not that a cube is off.'),
    'cube.overview': dict(title='Cube', what='This cube\'s number, tag and registration state, and what it was last told to show.',
                          check='Green registration means an application ACK was recorded; it does not prove the cube is reachable now.'),
    'cube.firmware': dict(title='Firmware', what='The version this cube reports over USB against the local build.',
                          check='A matching version is not a binary hash verification. Missing response means unverified, not current.'),
    'register': dict(title='Register cubes', what='Plug in a cube over USB: it is identified, given the lowest free number above 32 if it has none (write a new number on its label), flashes for its NFC tag at the pairing station, and after the cube acknowledges, one Sync uploads the mapping and publishes the zone database.',
                     check='Registered means the cube acknowledged over the radio. Zones learn the tag only once they hold the published database: automatic zone updates bring it to zones in range; Update all is the manual path.'),
    'flash': dict(title='Flash cubes', what='Switch on, then plug cubes in over USB one after another. Each gets the bundled firmware (skipped when this cube already completed this build) and the published main show: the cube\'s storage (NVS) is read over USB, and an older, missing or damaged show is replaced with every other value (number, tag, calibration) kept, read back, and must be reported by the cube after a restart. USB only; nothing goes over the radio.',
                  check='A firmware skip is the flasher\'s own record for this MAC and build. "Show written" is verified three ways: the NVS read back matches, nothing outside the show changed, and the cube\'s "?" answer reports the new version from NVS. The switch is off every time the console starts.'),
    'station': dict(title='Pairing station', what='The NFC station: discovery, registration, LED tests, and the zone relay.',
                    check='NFC ready and radio ready are separate. A registration needs the cube\'s application ACK.'),
    'zone.monitor': dict(title='Cube monitor', what='The cube on this plate and what the plate told it; the ring is the last commanded colour.',
                         check='Compare the ring with the real cube. "Delivered" is the radio ACK; "acknowledged" is the cube.'),
    'zone.firmware': dict(title='Firmware & database', what='Flash firmware + identity + database, or update only the database.',
                          check='Zones only accept a newer database version. A skipped board is already current.'),
    'dongle': dict(title='ESP-NOW dongle', what='Relays zone database updates and status queries over the radio.',
                   check='Update all needs the zones in range; a zone confirms by reporting the new version and CRC.'),
    'inventory': dict(title='Inventory & database', what='The local SQLite inventory, the published zone database and web sync.',
                      check='Mappings reach zones only after Sync publishes and a zone receives the new version.'),
    'workstation': dict(title='Workstation', what='One panel for every board that speaks the pairing protocol: a pairing station, an ESP-NOW dongle, a General Radio or a Workstation (NFC reader, pairing relay, zone updates, cube colours and the main show, a pool lamp through the central, a TouchDesigner cue through the bridge). Tabs light up for what the board\'s hello reports.',
                        check='A legacy station only reads tags and relays; it is left exactly as before. Set zone to ALL cubes is a broadcast that recolours the whole installation. Lamp and cue are leased: they drop when this page stops holding them.'),
    'workstation.cubes': dict(title='Cubes', what='Colour one cube (unicast, radio-acknowledged) or every cube in range (broadcast, never acknowledged), and start the main show. Shown when hello lists the cube role.',
                              check='Delivered means the cube\'s radio answered, not that it changed colour. Only mainshow-ready cubes start a show.'),
    'workstation.pool': dict(title='Pool lamp', what='Holds ONE pool member through the pool central, as an emulated slider radio (one slot per sender). Shown when hello lists the pool role.',
                             check='Real pool radios keep working alongside; the central lights a frame while any radio holds it.'),
    'workstation.preshow': dict(title='Preshow cue', what='Raises a TouchDesigner cue through the media bridge as a fifth plate; acknowledged end to end in modern mode. Shown when hello lists the preshow role.',
                                check='Switching points is OFF then ON. In legacy mode nothing can acknowledge the cue.'),
    'pool.recording': dict(title='Guided recording', what='Move the slider to each prompted tick, press Reached this position, hold still for the countdown; the analysis proposes filter tuning and measured control points.',
                           check='Endpoints are always included. Applying replaces measured control points and can save tuning to flash: note the previous values first.'),
    'inventory.plan': dict(title='What a Sync would move', what='Record by record: this computer, the web, and the result after the merge. Decided rows are where both sides changed and the newest change won.',
                           check='Check needs the web password and writes nothing. Sync applies downloads only while no operation runs here.'),
    'computer.intake': dict(title='USB intake', what='Automatic flashing for boards plugged in from now on: cubes get the bundled cube build; identified zone boards are updated in place, legacy sketches take the selected zone and point.',
                            check='Off at every launch. Remove other ESP32 boards from the bench first; a USB-compatible board is not proof of its role. Stop after current lets the running write finish.'),
    'show': dict(title='Show control', what='Make a cube mainshow-ready and trigger the main show through the Mainshow controller.',
                 check='Cubes report nothing back: the clock shows where the cube should be.'),
    'pool.calibration': dict(title='Pool calibration', what='Slider distance to member index, with a leased output override.',
                             check='The override drops 1.5 s after the console stops pinging it.'),
    'preshow.cue': dict(title='Cue test', what='Raise TouchDesigner cues through this plate without a reader.',
                        check='In legacy mode nothing can acknowledge a cue; that is expected with the original bridge.'),
    'rangetest': dict(title='Range test', what='Link quality between the exhibition space and the back room.',
                      check='Nothing is written to disk.'),
    'pooltest': dict(title='Pool light test', what='Emulates all six pool radios to exercise the lights.',
                     check='Power off real pool radios first: this bridge uses their ids 1-6.'),
    'inventory.zonedb': dict(title='Zone database', what='The published cube database (web-allocated version) and what every zone last reported holding.',
                             check='Versions only increase. A zone "ahead" of this computer means another computer published; pull, then publish again.'),
    'inventory.websync': dict(title='Web sync', what='Uploads local inventory changes, downloads web changes and publishes/pulls the zone database.',
                              check='Sync never asks for a decision: the newest change wins and is audited. Downloads wait while a hardware operation runs.'),
    'bench': dict(title='Bench tools', what='Diagnostics that need a specific board on USB; the board\'s identity is what makes them safe.',
                  check='Light and cue tests affect physical output. Switch overrides off afterwards.'),
    'settings': dict(title='Settings', what='Appearance and behaviour of this console; nothing here changes hardware.',
                     check='Theme is per browser; behaviour and automatic-update settings are saved on this computer.'),
}

STATUS = {
    'registration.acknowledged': dict(label='Registered · ACK', tone='ok', tip='A matching application ACK arrived. It does not prove flash persistence or LED output.'),
    'registration.unconfirmed': dict(label='Unconfirmed', tone='warn', tip='The result is uncertain; retrying the same ID/UID is safe.'),
    'registration.pending': dict(label='Registering', tone='info', tip='Waiting for the cube\'s acknowledgment.'),
    'registration.not_transmitted': dict(label='Saved · not sent', tone='info', tip='A trusted mapping this computer has not transmitted.'),
    'registration.awaiting_tag': dict(label='Needs NFC tag', tone='info', tip='Numbered, waiting for a tag scan at the station.'),
    'registration.needs_number': dict(label='Needs number', tone='bad', tip='Without a number a device stays out of the zone database.'),
    'registration.discovered': dict(label='Unregistered', tone='muted', tip='Answered discovery; nothing saved for it.'),
    'delivery.delivered': dict(label='Delivered', tone='info', tip='Radio acknowledgment only. Delivered ≠ acknowledged by the application.'),
    'delivery.acknowledged': dict(label='Acknowledged', tone='ok', tip='The device answered.'),
    'delivery.verified': dict(label='Verified', tone='ok', tip='Read back independently.'),
    'delivery.unconfirmed': dict(label='No radio ACK', tone='warn', tip='The radio did not confirm delivery; the cube may be off, out of range or on another channel.'),
    'firmware.current': dict(label='Version matches', tone='ok', tip='Reported version equals the local build. Not a binary hash check.'),
    'firmware.different': dict(label='Update needed', tone='warn', tip='The reported version differs from the local build.'),
    'firmware.unknown': dict(label='Not verified', tone='warn', tip='No matching answer to "?". Unverified is not the same as current.'),
    'radio.recent': dict(label='Heard', tone='ok', tip='A discovery reply within the last 10 s.'),
    'radio.stale': dict(label='Not heard', tone='muted', tip='No discovery reply this session. A grey dot does not mean the cube is off.'),
    'zonedb.current': dict(label='Current', tone='ok', tip='Version and CRC match the published database.'),
    'zonedb.behind': dict(label='Out of date', tone='warn', tip='An older version; update over USB or over the air.'),
    'zonedb.ahead': dict(label='Newer / differs', tone='bad', tip='Higher or equal version with different content; only a new publication fixes it.'),
    'zonedb.updating': dict(label='Updating', tone='info', tip='Staging chunks; the zone discards a partial update after 60 s.'),
    'zonedb.unpublished': dict(label='Nothing published', tone='bad', tip='Publish a zone database first (Sync).'),
    'nfc.ok': dict(label='NFC scanning', tone='ok', tip='The reader answers and polls.'),
    'nfc.warn': dict(label='NFC degraded', tone='warn', tip='The reader answers but scan commands fail on I²C.'),
    'nfc.bad': dict(label='NFC not responding', tone='bad', tip='The PN532 is not answering; the plate keeps its radio.'),
    'usb.present': dict(label='USB', tone='info', tip='Enumerated; not identified yet.'),
    'usb.probing': dict(label='Identifying…', tone='info', tip='Asking the board what it is (no reset).'),
    'usb.session': dict(label='Live', tone='ok', tip='The console holds this port.'),
    'usb.job': dict(label='Busy', tone='info', tip='A job is using this port.'),
    'usb.foreign': dict(label='Held elsewhere', tone='warn', tip='Another application owns this port.'),
    'usb.protected': dict(label='Protected', tone='muted', tip='The installed pairing station\'s identity: never probed or flashed.'),
    'usb.idle': dict(label='Identified', tone='muted', tip='Identified; no session open.'),
    'sync.ok': dict(label='Synced', tone='ok', tip='Up to date with the web.'),
    'sync.pending': dict(label='Sync pending', tone='warn', tip='Changes to upload or download.'),
    'sync.offline': dict(label='Offline', tone='muted', tip='The web is unreachable; working locally.'),
    'sync.error': dict(label='Sync problem', tone='bad', tip='The web could not answer.'),
}

# Tooltip copy per command: label, what (what happens), hazard (physical or irreversible effect, shown with ▲),
# needs (preconditions), disabled (a generic reason when the button is unavailable). Panels may override any of
# these per button. Every hardware/destructive command must have an entry with `what` and `hazard`.
_STATION = 'The pairing station connected on USB.'
_RADIO = 'A connected Workstation (or a General Radio) that relays show frames.'
ACTIONS = {
    # --- zones: USB
    'zone.update_db_usb': dict(label='Update database over USB', what='Writes only the published cube database into this zone board\'s database slot. Firmware and identity are untouched.',
                               hazard='Writes flash and reboots the board; the zone is out of service for a few seconds.',
                               needs='A published zone database newer than the one on the board.', disabled='The board already holds the published database, has no published database to take, or a job is running.'),
    'zone.flash': dict(label='Flash firmware + identity + database', what='Builds (if needed) and writes the zone firmware, its identity (kind, point, name) and the published database, then verifies it boots.',
                       hazard='Writes flash and reboots the board. Choose the zone and point carefully: they decide what this plate does in the show.',
                       needs='An identified zone board and a current zone build.', disabled='A job is running, the build failed, or the inventory refused this board (see Force flash).'),
    'zone.flash_force': dict(label='Force flash (overwrite)', what='Flashes a board the inventory lists as a cube or an excluded device (reader, station, dongle).',
                             hazard='Overwrites whatever the board was. A cube loses its LED firmware and is unregistered. Hold to confirm.'),
    'zone.detect': dict(label='Identify via bootloader', what='Reads the board\'s flash through its ROM bootloader to find out which firmware and identity it holds.',
                        hazard='Resets the board into the bootloader and reboots it afterwards.', needs='A board on USB that did not answer the normal probe.'),
    'zone.check_report': dict(label='Read zone report', what='Opens the serial port and asks the zone for its report (?): version, identity, database and reader state.',
                              hazard='Opening the port can reset some boards.'),
    'zone.rxgain_usb': dict(label='Apply RX gain', what='Stores the PN532 reader gain on the zone and applies it immediately.',
                            hazard='Changes how far away a tag is read on this plate; saved to the board.'),
    'zone.nfc_recover': dict(label='Recover NFC reader', what='Clears the I²C bus and re-initialises the zone\'s PN532.',
                             hazard='The reader is offline for a moment; a tag on the plate is re-read.'),
    # --- zones: over the air
    'zones.update': dict(label='Update database over the air', what='Sends the published database to this one zone: unicast announce, then broadcast chunks until it reports the new version and CRC.',
                         hazard='The zone rewrites its database slot while the transfer runs; keep the dongle in range.', needs=_RADIO + ' The zone must be behind.',
                         disabled='The zone is already current, or no radio is connected.'),
    'zones.update_all': dict(label='Update all out-of-date zones', what='One broadcast run that brings every in-range zone that is behind up to the published database.',
                             hazard='Every behind zone in range rewrites its database. Zones confirm with version + CRC.', needs=_RADIO,
                             disabled='No radio connected, or no zone is behind.'),
    'zones.reboot': dict(label='Reboot', what='Sends ZONE_REBOOT to this zone over the radio.', hazard='The zone restarts and misses tags for a few seconds.', needs=_RADIO),
    'zones.set_rx_gain': dict(label='Set RX gain', what='Sends ZONE_SET_CONFIG with a new reader gain.',
                              hazard='Changes the plate\'s read range; confirmed only by the zone\'s next settings report.', needs=_RADIO),
    # --- cubes / pairing
    'cube.flash_firmware': dict(label='Flash cube firmware', what='Writes the bundled cube firmware, verifies it and checks the boot message, then brings the show in its storage up to the published one.',
                                hazard='Writes the app partition and reboots the cube. NVS (number and tag registration) is preserved; only the show in it is replaced when older.',
                                needs='A cube on USB and a current cube build.', disabled='A job is running on this board.'),
    'cube.update_show': dict(label='Update show over USB', what='Writes the published main show into this cube\'s storage (NVS) over USB, keeping every other value, reads it back and checks the cube reports it. Firmware untouched.',
                             hazard='Rewrites the cube\'s NVS partition and restarts the cube. The previous contents are kept in the run folder.',
                             needs='A cube identified over USB with firmware v1.5.0 or later, and a published show.', disabled='A job is running on this board.'),
    'flash.enable': dict(label='Flash cubes as they are plugged in', what='Every cube on USB, already plugged in or plugged in later, gets the firmware and the published show over USB, once per plug-in.',
                         hazard='Writes firmware and NVS on every cube plugged in while it is on.'),
    'flash.retry': dict(label='Retry (rewrite the firmware)', what='Flashes the failed cube again, rewriting the firmware even if it is current (the Tk flasher\'s Manual Retry), then the show.',
                        hazard='Writes the app partition and may rewrite the show in NVS.'),
    'dongle.flash': dict(label='Write Workstation / controller firmware', what='Turns a spare ESP32-C3 into a Workstation or the Mainshow controller.',
                         hazard='Replaces whatever firmware the board had; a full backup is taken the first time.', needs='A spare board on USB that is not a cube in use.'),
    'dongle.flash_force': dict(label='Force write Workstation / controller firmware', what='Writes the Workstation or Mainshow controller firmware to a board the inventory protects (a zone, cube, controller or the station).',
                               hazard='Overwrites whatever the board was: a zone leaves the show, a cube loses its LED firmware. A full backup is taken the first time. Hold to confirm.'),
    'pairing.register': dict(label='Register (scan a tag)', what='Flashes this cube red/blue and waits for a fresh NFC scan at the station, then sends it its number and tag.',
                             hazard='A scanned tag that belongs to another device is transferred to this cube.', needs='Station connected and its NFC reader ready.',
                             disabled='The station is not connected, its reader is not ready, or another operation is running.'),
    'register.restart': dict(label='Start again', what='Runs the registration workflow again for the cube plugged in over USB: number, NFC scan, sync.',
                             hazard='The cube flashes red/blue and waits for a fresh scan; a scanned tag that belongs to another device is transferred to it.', needs=_STATION),
    'register.retry': dict(label='Retry', what='Retries the failed step: re-sends the saved registration if the station paused on this cube, otherwise flashes it for a new scan, or syncs again.',
                           hazard='The cube stores the mapping in NVS; a pending tag is confirmed only by its ACK.', needs=_STATION),
    'pairing.transmit': dict(label='Send saved mapping', what='Sends this cube its saved number and tag without a new scan.',
                             hazard='The cube stores the mapping in NVS; a pending tag is confirmed only by its ACK.', needs=_STATION),
    'pairing.transmit_originals': dict(label='Transmit original 32', what='Sends each of the original 32 mappings to its cube.',
                                       hazard='Rewrites the number/tag on every original cube in range; changed originals are refused.', needs=_STATION),
    'pairing.retry_unconfirmed': dict(label='Retry unconfirmed', what='Retransmits every saved registration that has no application ACK yet.',
                                      hazard='Sends to many cubes in turn.', needs=_STATION),
    'pairing.start_pair': dict(label='Pair new cubes (auto)', what='Discovers unregistered cubes, flashes each in turn and waits for its tag to be scanned.',
                               hazard='Assigns numbers automatically (lowest free above 32, never 2, 22, 39 or 43).', needs='Station connected, NFC reader ready, no other operation running.'),
    'pairing.retry': dict(label='Retry paused', what='Resumes the paused registration for the same cube.', hazard='The cube flashes again and waits for a scan.', needs=_STATION),
    'station.nfc_recover': dict(label='Recover NFC reader', what='I²C bus clear and PN532 re-initialisation on the pairing station.',
                                hazard='The reader is offline for a moment. Refused while an operation runs.', needs=_STATION),
    'inventory.unregister': dict(label='Unregister', what='Releases this device\'s number and tags in the local inventory.',
                                 hazard='The cube\'s own firmware still holds the old mapping until it is registered again. Hold to confirm.'),
    # --- show
    'mainshow.ready': dict(label='① Mainshow ready', what='SET_ZONE 4 to this cube: it turns neon and becomes eligible for the main show.',
                           hazard='Changes the cube\'s colour immediately.', needs='A Mainshow controller or Workstation connected.'),
    'mainshow.trigger': dict(label='② Trigger mainshow', what='Sends a fresh showId five times to this cube.',
                             hazard='Starts the show on the cube; only a mainshow-ready cube starts.', needs='A Mainshow controller or Workstation connected.'),
    'mainshow.idle': dict(label='Stop → idle', what='SET_ZONE 0: ends the show on this cube and returns it to idle white.', hazard='Interrupts a running show on this cube.'),
    'mainshow.trigger_all': dict(label='Trigger the main show on all ready cubes', what='Broadcasts a fresh showId to every mainshow-ready cube in range.',
                                 hazard='Broadcast, no acknowledgment; cannot be undone. Hold to confirm.'),
    'mainshow.led_test': dict(label='LED test', what='Lights or clears the controller\'s own LED.', hazard='Visible on the controller only.'),
    'show.query': dict(label='Query cubes', what='Broadcast SHOW_QUERY: every v1.5.0+ cube in range reports which show it holds within 2 s.', hazard='Radio traffic only; nothing changes on the cubes.', needs=_RADIO),
    'show.update': dict(label='Update', what='Sends the published show to this one cube.', hazard='The cube stores the new show; a cube never goes back a version.', needs=_RADIO),
    'show.update_selected': dict(label='Update selected', what='Sends the published show until the ticked cubes confirm it.',
                                 hazard='A broadcast: every cube in range on an older show stores it too (all cubes get the same show).',
                                 needs=_RADIO + ' A published show.'),
    'show.update_all': dict(label='Update all', what='Broadcasts the published show until every cube heard recently confirms it.',
                            hazard='Every cube in range stores the new show. Cubes playing a show commit it when their show ends.', needs=_RADIO + ' A published show.'),
    'show.auto_update': dict(label='Auto update', what='Walk-around mode: any cube in range on an older show is updated automatically.',
                             hazard='Keeps transmitting while on; switch it off when you are done.', needs=_RADIO),
    'show.push_config': dict(label='Send length to controller', what='Tells the Mainshow controller (mainshow-1.3.0+) the published show\'s length so it bounds its timecode.',
                             hazard='Changes how long the controller runs a show.'),
    'show.revert': dict(label='Revert', what='Replaces the editor\'s working copy with the published show or the compiled-in default.',
                        hazard='Discards this computer\'s unsaved edits. Hold to confirm.'),
    'show.live': dict(label='Mirror on real cubes', what='While on, broadcasts the colour each previewed cube number shows at the playhead (SHOW_LIVE, about 16 times a second) so the bench cubes follow the editor.',
                      hazard='Recolours every cube in range whose number is previewed; each colour lapses 0.6 s after the last one. Cubes playing a show ignore it.',
                      needs='A Workstation (or General Radio general-radio-1.2.0) and cubes with firmware v1.7.0-USB.1.'),
    'show.publish': dict(label='Publish', what='Publishes the working copy on the web as the next show version.', hazard='Cubes are not touched until you update them.'),
    # --- workstation radio verbs
    'radio.set_zone': dict(label='Set zone', what='Unicast SET_ZONE ×3 to the chosen cube through the Workstation.',
                           hazard='Recolours the cube; the radio ACK is not proof it changed colour.', needs='Workstation connected and a cube chosen.'),
    'radio.set_zone_all': dict(label='Set zone on ALL cubes', what='Broadcast SET_ZONE to every cube that hears it.',
                               hazard='Recolours the whole installation in range, never acknowledged. Hold to confirm.'),
    'radio.show_start': dict(label='Start show on this cube', what='MSG_SHOW_START with a fresh showId ×5 to the chosen cube.',
                             hazard='Starts the show; only a mainshow-ready cube starts.', needs='Workstation connected and a cube chosen.'),
    'radio.show_start_all': dict(label='Start show on ALL ready cubes', what='Broadcast MSG_SHOW_START to every mainshow-ready cube in range.',
                                 hazard='Broadcast, no acknowledgment; cannot be undone. Hold to confirm.'),
    'radio.identify': dict(label='Identify', what='Makes the chosen cube blink blue/red so you can find it.', hazard='Visible on the cube; it returns to idle afterwards.', needs='Workstation connected and a cube chosen.'),
    'radio.reader_flash': dict(label='Flash the cube when its tag is read', what='Each tag placed on this board\'s reader makes the cube that owns it flash blue/red for 2 s over the radio, so you can see the tag, the inventory and the radio all agree.',
                               hazard='Visible on the cube; it returns to idle afterwards. Only while the board is idle, never during pairing or registration.', needs='A Workstation (or pairing station) with its NFC reader working.'),
    'radio.transmit': dict(label='Send saved mapping', what='Registers the saved number and tag on the chosen cube over the air (three attempts, then the cube\'s acknowledgment).',
                           hazard='The cube stores the mapping in NVS.', needs='Workstation connected; the cube has a saved tag.'),
    'radio.pool': dict(label='Hold pool lamp', what='Holds one pool member through the pool central as an emulated slider radio.',
                       hazard='Lights a real pool lamp while held; released when this page stops holding it.', needs='Workstation connected; pool central in range.'),
    'radio.preshow': dict(label='Raise preshow cue', what='Raises a TouchDesigner cue for a preshow point through the media bridge.',
                          hazard='Triggers media in the room; held only while this page holds it.', needs='Workstation connected; preshow bridge in range.'),
    'radio.led_test': dict(label='LED test', what='Cycles the board\'s eight WS2812 LEDs.', hazard='Visible on the dongle only.'),
    # --- pool / preshow plates, bench tools
    'pool.arm': dict(label='Override output without a cube', what='Lets the slider drive the pool lights with no cube on the plate (the board\'s leased host override).',
                     hazard='Lights real pool lamps. Leased: the console pings every 0.35 s and the lease lapses 1.5 s after it stops.', needs='A pool radio on USB, ready.'),
    'pool.cal_save': dict(label='Apply & save to flash', what='Writes the calibration control points to the radio\'s flash.', hazard='Replaces the saved calibration; note the previous values first.'),
    'pool.assign_radio_id': dict(label='Assign radio id', what='Stores a new radio id (1-6) on this pool radio.', hazard='Two radios with the same id fight over the same pool slot.'),
    'pool.flash_firmware': dict(label='Flash pool firmware', what='Writes the current PoolZone firmware to this radio.', hazard='Writes flash and reboots. Pool radios and the pool central are a matched set.'),
    'pool.record_start': dict(label='Start guided recording', what='The radio streams raw slider samples while the page prompts each position.', hazard='The plate does not drive the lights normally while recording.'),
    'pool.record_apply': dict(label='Apply recording', what='Applies the recording\'s recommended tuning, and optionally its measured control points.', hazard='Can save tuning and control points to flash.'),
    'preshow.arm': dict(label='Cue override', what='Starts the plate\'s leased host override so the POINT buttons can raise cues without a reader.',
                        hazard='Leased 1.5 s: the console keeps it alive while on. Switch it off when done.', needs='A preshow plate on USB.'),
    'preshow.cue': dict(label='Cue', what='Raises or drops a TouchDesigner cue through this plate.', hazard='Triggers media in the room.', needs='The cue override switched on.', disabled='Switch the cue override on first.'),
    'bridge.test': dict(label='Test cue', what='Writes PRESHOW,n,ON|OFF to TouchDesigner directly from the bridge.', hazard='Triggers media in the room.'),
    'central.recover': dict(label='Recover I²C', what='Re-initialises both PCA9685 boards on the pool central.', hazard='Pool outputs blink off and back on.'),
    'pooltest.toggle': dict(label='Toggle member', what='Switches one pool member on or off through the emulated radios.', hazard='Lights real pool lamps.'),
    'pooltest.sequential': dict(label='Sequential test', what='Lights each pool member in turn.', hazard='Lights real pool lamps; power off the real pool radios first.'),
    'pooltest.channel': dict(label='Apply channel', what='Changes the test bridge\'s ESP-NOW channel.', hazard='Refused while any light is on. The installation uses channel 2.'),
    'monitor.zone': dict(label='Set zone', what='Sends SET_ZONE to the cube on this plate.', hazard='Recolours the cube.'),
    'monitor.clear': dict(label='Clear', what='Sends SET_ZONE 0 to the cube on this plate.', hazard='Returns the cube to idle white.'),
    'usb.auto_cubes': dict(label='Auto-flash cubes', what='Every cube plugged in from now on gets the bundled cube firmware and the published show, one after another (the Flash page\'s switch).',
                           hazard='Writes flash on every cube you plug in. Remove other ESP32 boards from the bench first. Off at every launch.'),
    'usb.auto_zones': dict(label='Auto-flash zones', what='Every zone board plugged in from now on is updated in place; legacy sketches take the selected zone and point.',
                           hazard='Writes flash on every zone board you plug in. Off at every launch.'),
    # --- safe but worth explaining
    'device.probe': dict(label='Probe again', what='Asks the board what it is again, without resetting it.'),
    'sync.run': dict(label='Sync', what='Uploads local inventory changes, downloads web changes, and publishes or pulls the zone database.', hazard='Newest change wins; decisions are audited and reported.'),
    'zone.publish': dict(label='Publish zone database', what='Publishes the local cube mapping as the next web-allocated zone database version.', hazard='Zones only pick it up once updated (USB or over the air).'),
}

GLOSSARY = {
    'pending_uid': 'A proposed tag, retryable; not the committed tag.',
    'uid': 'The committed NFC tag.',
    'excluded': 'A reader, station or dongle: never a cube.',
    'reserved numbers': '2, 22, 39 and 43 are never allocated automatically.',
}


def as_dict():
    return dict(tones=TONES, glyphs=GLYPHS, ladder=LADDER, panels=PANELS, status=STATUS, actions=ACTIONS, glossary=GLOSSARY)
